use super::super::system::current_virtualization_log_snapshot;

pub(crate) fn log_virtualization_platform_lifecycle() {
    let virt = current_virtualization_log_snapshot();
    aethercore::klog_info!(
        "Virtualization lifecycle: backend={} summary={} progress={}‰ detect={} prepare={} capability={} feature={} launch={} resume={} trap={} step={} runtime_mode={} strategy={} budget={} dispatch={} preemption={} sched_lane={} dispatch_window={} exec_profile={} exec_scope={} governor_profile={} governor_scope={} governor={} latency_bias={} energy_bias={} aux={} class={} blocked_by={:?} policy_limited_by={:?} policy_scope={} entry_scope={} resume_scope={} trap_scope={} nested_scope={} time_scope={} passthrough_scope={} entry_mode={} resume_mode={} trap_mode={} nested_mode={} time_mode={} passthrough_mode={}",
        virt.backend,
        virt.lifecycle_summary,
        virt.lifecycle_progress_per_mille,
        virt.detect_state,
        virt.prepare_state,
        virt.capability_state,
        virt.feature_state,
        virt.launch_state,
        virt.resume_state,
        virt.trap_state,
        virt.runtime_step,
        virt.selected_mode,
        virt.runtime_strategy,
        virt.runtime_budget_class,
        virt.dispatch_class,
        virt.preemption_policy,
        virt.scheduler_lane,
        virt.dispatch_window,
        virt.execution_profile,
        virt.execution_profile_scope,
        virt.governor_profile,
        virt.governor_profile_scope,
        virt.governor_class,
        virt.latency_bias,
        virt.energy_bias,
        virt.aux_step,
        virt.operation_class,
        virt.blocked_by,
        virt.policy_limited_by,
        virt.policy_scope,
        virt.entry_scope,
        virt.resume_scope,
        virt.trap_scope,
        virt.nested_scope,
        virt.time_scope,
        virt.passthrough_scope,
        virt.entry_mode,
        virt.resume_mode,
        virt.trap_mode,
        virt.nested_mode,
        virt.time_mode,
        virt.passthrough_mode
    );
}
