use super::ModifierState;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
#[allow(dead_code)]
pub enum Keycode {
    Unknown = 0,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Backquote,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    Minus,
    Equal,
    Backspace,
    Tab,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LeftBracket,
    RightBracket,
    Backslash,
    CapsLock,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Quote,
    Enter,
    LeftShift,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Period,
    Slash,
    RightShift,
    LeftCtrl,
    LeftAlt,
    Space,
    RightAlt,
    RightCtrl,
    Insert,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    Up,
    Down,
    Left,
    Right,
    NumLock,
    ScrollLock,
    PrintScreen,
    Pause,
    NumpadSlash,
    NumpadStar,
    NumpadMinus,
    NumpadPlus,
    NumpadEnter,
    NumpadDot,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
}

pub(super) fn scancode_set1_to_keycode(scancode: u8) -> Keycode {
    match scancode {
        0x01 => Keycode::Escape,
        0x02 => Keycode::Key1,
        0x03 => Keycode::Key2,
        0x04 => Keycode::Key3,
        0x05 => Keycode::Key4,
        0x06 => Keycode::Key5,
        0x07 => Keycode::Key6,
        0x08 => Keycode::Key7,
        0x09 => Keycode::Key8,
        0x0A => Keycode::Key9,
        0x0B => Keycode::Key0,
        0x0C => Keycode::Minus,
        0x0D => Keycode::Equal,
        0x0E => Keycode::Backspace,
        0x0F => Keycode::Tab,
        0x10 => Keycode::Q,
        0x11 => Keycode::W,
        0x12 => Keycode::E,
        0x13 => Keycode::R,
        0x14 => Keycode::T,
        0x15 => Keycode::Y,
        0x16 => Keycode::U,
        0x17 => Keycode::I,
        0x18 => Keycode::O,
        0x19 => Keycode::P,
        0x1A => Keycode::LeftBracket,
        0x1B => Keycode::RightBracket,
        0x1C => Keycode::Enter,
        0x1D => Keycode::LeftCtrl,
        0x1E => Keycode::A,
        0x1F => Keycode::S,
        0x20 => Keycode::D,
        0x21 => Keycode::F,
        0x22 => Keycode::G,
        0x23 => Keycode::H,
        0x24 => Keycode::J,
        0x25 => Keycode::K,
        0x26 => Keycode::L,
        0x27 => Keycode::Semicolon,
        0x28 => Keycode::Quote,
        0x29 => Keycode::Backquote,
        0x2A => Keycode::LeftShift,
        0x2B => Keycode::Backslash,
        0x2C => Keycode::Z,
        0x2D => Keycode::X,
        0x2E => Keycode::C,
        0x2F => Keycode::V,
        0x30 => Keycode::B,
        0x31 => Keycode::N,
        0x32 => Keycode::M,
        0x33 => Keycode::Comma,
        0x34 => Keycode::Period,
        0x35 => Keycode::Slash,
        0x36 => Keycode::RightShift,
        0x37 => Keycode::NumpadStar,
        0x38 => Keycode::LeftAlt,
        0x39 => Keycode::Space,
        0x3A => Keycode::CapsLock,
        0x3B => Keycode::F1,
        0x3C => Keycode::F2,
        0x3D => Keycode::F3,
        0x3E => Keycode::F4,
        0x3F => Keycode::F5,
        0x40 => Keycode::F6,
        0x41 => Keycode::F7,
        0x42 => Keycode::F8,
        0x43 => Keycode::F9,
        0x44 => Keycode::F10,
        0x45 => Keycode::NumLock,
        0x46 => Keycode::ScrollLock,
        0x47 => Keycode::Numpad7,
        0x48 => Keycode::Numpad8,
        0x49 => Keycode::Numpad9,
        0x4A => Keycode::NumpadMinus,
        0x4B => Keycode::Numpad4,
        0x4C => Keycode::Numpad5,
        0x4D => Keycode::Numpad6,
        0x4E => Keycode::NumpadPlus,
        0x4F => Keycode::Numpad1,
        0x50 => Keycode::Numpad2,
        0x51 => Keycode::Numpad3,
        0x52 => Keycode::Numpad0,
        0x53 => Keycode::NumpadDot,
        0x57 => Keycode::F11,
        0x58 => Keycode::F12,
        _ => Keycode::Unknown,
    }
}

pub fn keycode_to_ascii(keycode: Keycode, mods: &ModifierState) -> Option<u8> {
    let shifted = mods.shift() ^ mods.caps_lock;

    match keycode {
        Keycode::Key1 => Some(if mods.shift() { b'!' } else { b'1' }),
        Keycode::Key2 => Some(if mods.shift() { b'@' } else { b'2' }),
        Keycode::Key3 => Some(if mods.shift() { b'#' } else { b'3' }),
        Keycode::Key4 => Some(if mods.shift() { b'$' } else { b'4' }),
        Keycode::Key5 => Some(if mods.shift() { b'%' } else { b'5' }),
        Keycode::Key6 => Some(if mods.shift() { b'^' } else { b'6' }),
        Keycode::Key7 => Some(if mods.shift() { b'&' } else { b'7' }),
        Keycode::Key8 => Some(if mods.shift() { b'*' } else { b'8' }),
        Keycode::Key9 => Some(if mods.shift() { b'(' } else { b'9' }),
        Keycode::Key0 => Some(if mods.shift() { b')' } else { b'0' }),
        Keycode::A => Some(if shifted { b'A' } else { b'a' }),
        Keycode::B => Some(if shifted { b'B' } else { b'b' }),
        Keycode::C => Some(if shifted { b'C' } else { b'c' }),
        Keycode::D => Some(if shifted { b'D' } else { b'd' }),
        Keycode::E => Some(if shifted { b'E' } else { b'e' }),
        Keycode::F => Some(if shifted { b'F' } else { b'f' }),
        Keycode::G => Some(if shifted { b'G' } else { b'g' }),
        Keycode::H => Some(if shifted { b'H' } else { b'h' }),
        Keycode::I => Some(if shifted { b'I' } else { b'i' }),
        Keycode::J => Some(if shifted { b'J' } else { b'j' }),
        Keycode::K => Some(if shifted { b'K' } else { b'k' }),
        Keycode::L => Some(if shifted { b'L' } else { b'l' }),
        Keycode::M => Some(if shifted { b'M' } else { b'm' }),
        Keycode::N => Some(if shifted { b'N' } else { b'n' }),
        Keycode::O => Some(if shifted { b'O' } else { b'o' }),
        Keycode::P => Some(if shifted { b'P' } else { b'p' }),
        Keycode::Q => Some(if shifted { b'Q' } else { b'q' }),
        Keycode::R => Some(if shifted { b'R' } else { b'r' }),
        Keycode::S => Some(if shifted { b'S' } else { b's' }),
        Keycode::T => Some(if shifted { b'T' } else { b't' }),
        Keycode::U => Some(if shifted { b'U' } else { b'u' }),
        Keycode::V => Some(if shifted { b'V' } else { b'v' }),
        Keycode::W => Some(if shifted { b'W' } else { b'w' }),
        Keycode::X => Some(if shifted { b'X' } else { b'x' }),
        Keycode::Y => Some(if shifted { b'Y' } else { b'y' }),
        Keycode::Z => Some(if shifted { b'Z' } else { b'z' }),
        Keycode::Space => Some(b' '),
        Keycode::Enter | Keycode::NumpadEnter => Some(b'\n'),
        Keycode::Tab => Some(b'\t'),
        Keycode::Backspace => Some(0x08),
        Keycode::Minus => Some(if mods.shift() { b'_' } else { b'-' }),
        Keycode::Equal => Some(if mods.shift() { b'+' } else { b'=' }),
        Keycode::LeftBracket => Some(if mods.shift() { b'{' } else { b'[' }),
        Keycode::RightBracket => Some(if mods.shift() { b'}' } else { b']' }),
        Keycode::Backslash => Some(if mods.shift() { b'|' } else { b'\\' }),
        Keycode::Semicolon => Some(if mods.shift() { b':' } else { b';' }),
        Keycode::Quote => Some(if mods.shift() { b'"' } else { b'\'' }),
        Keycode::Backquote => Some(if mods.shift() { b'~' } else { b'`' }),
        Keycode::Comma => Some(if mods.shift() { b'<' } else { b',' }),
        Keycode::Period => Some(if mods.shift() { b'>' } else { b'.' }),
        Keycode::Slash => Some(if mods.shift() { b'?' } else { b'/' }),
        Keycode::NumpadSlash => Some(b'/'),
        Keycode::NumpadStar => Some(b'*'),
        Keycode::NumpadMinus => Some(b'-'),
        Keycode::NumpadPlus => Some(b'+'),
        Keycode::NumpadDot => Some(b'.'),
        Keycode::Numpad0 => Some(b'0'),
        Keycode::Numpad1 => Some(b'1'),
        Keycode::Numpad2 => Some(b'2'),
        Keycode::Numpad3 => Some(b'3'),
        Keycode::Numpad4 => Some(b'4'),
        Keycode::Numpad5 => Some(b'5'),
        Keycode::Numpad6 => Some(b'6'),
        Keycode::Numpad7 => Some(b'7'),
        Keycode::Numpad8 => Some(b'8'),
        Keycode::Numpad9 => Some(b'9'),
        _ => None,
    }
}
