use super::SyscallStatus;

pub(crate) struct SyscallDef {
    pub(crate) name: &'static str,
    pub(crate) family: &'static str,
    pub(crate) status: SyscallStatus,
    pub(crate) location: &'static str,
    pub(crate) issues: &'static [&'static str],
    pub(crate) tests: &'static [&'static str],
    pub(crate) dependencies: &'static [&'static str],
}

pub(crate) fn get_glibc_inventory() -> Vec<SyscallDef> {
    vec![
        // CRITICAL_FILE_IO (12)
        SyscallDef {
            name: "read",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/io_support.rs:125",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &[],
        },
        SyscallDef {
            name: "write",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/io_support.rs:171",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &[],
        },
        SyscallDef {
            name: "open",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/io_support.rs:78",
            issues: &[],
            tests: &["fs_tests.rs"],
            dependencies: &["getcwd", "namespace"],
        },
        SyscallDef {
            name: "openat",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/fs/file.rs",
            issues: &["flags via openat2"],
            tests: &["fs_tests.rs"],
            dependencies: &["dirfd resolution"],
        },
        SyscallDef {
            name: "lseek",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/io_support.rs",
            issues: &[],
            tests: &["fs_tests.rs"],
            dependencies: &["fd table"],
        },
        SyscallDef {
            name: "getdents64",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/fs/dir.rs",
            issues: &[],
            tests: &["fs_tests.rs"],
            dependencies: &["readdir infrastructure"],
        },
        SyscallDef {
            name: "pread64",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/io_support.rs:149",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["lseek consistency"],
        },
        SyscallDef {
            name: "pwrite64",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/io_support.rs:202",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["lseek consistency"],
        },
        SyscallDef {
            name: "fallocate",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/fs/allocation_support.rs",
            issues: &[],
            tests: &["fs_tests.rs"],
            dependencies: &["VFS backend"],
        },
        SyscallDef {
            name: "fstat",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/fs/attr.rs",
            issues: &[],
            tests: &["fs_tests.rs"],
            dependencies: &["inode metadata"],
        },
        SyscallDef {
            name: "statx",
            family: "file_io",
            status: SyscallStatus::Partial,
            location: "kernel/src/modules/linux_compat/fs/attr.rs:151",
            issues: &["supports STATX_BASIC_STATS only; extended attributes need work"],
            tests: &["fs_tests.rs"],
            dependencies: &["fstat infrastructure"],
        },
        SyscallDef {
            name: "fstatat",
            family: "file_io",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/fs/attr.rs",
            issues: &[],
            tests: &["fs_tests.rs"],
            dependencies: &["dirfd resolution"],
        },
        // CRITICAL_PROCESS (9)
        SyscallDef {
            name: "fork",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/process/lifecycle.rs:166",
            issues: &["TODO: setpgid integration"],
            tests: &["p0_integration_harness.rs", "fork_cow_integration.rs"],
            dependencies: &["signal mask", "memory layout", "fd table"],
        },
        SyscallDef {
            name: "clone",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/process/lifecycle.rs:8",
            issues: &["namespace flags return EINVAL; CLONE_NEW* not supported"],
            tests: &["cross_feature_ipc_fallback.rs", "fork_cow_integration.rs"],
            dependencies: &["fork", "thread TLS", "tid management"],
        },
        SyscallDef {
            name: "execve",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/process/exec.rs",
            issues: &[],
            tests: &["p0_integration_harness.rs"],
            dependencies: &["VFS (ELF)", "signal reset"],
        },
        SyscallDef {
            name: "wait4",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/process/wait.rs:17",
            issues: &[],
            tests: &["p0_integration_harness.rs"],
            dependencies: &["process exit tracking", "zombie reaping"],
        },
        SyscallDef {
            name: "waitpid",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/process/wait.rs:81",
            issues: &[],
            tests: &["p0_integration_harness.rs"],
            dependencies: &["wait4", "process group tracking"],
        },
        SyscallDef {
            name: "prctl",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sys/advanced/handlers/misc_kernel_apis.rs",
            issues: &["partial flags (PR_PDEATHSIG, PR_SET_PTRACER, etc.)"],
            tests: &["sys/advanced/mod.rs"],
            dependencies: &["signal delivery", "capabilities"],
        },
        SyscallDef {
            name: "getpid",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/process.rs:199",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["task scheduler"],
        },
        SyscallDef {
            name: "gettid",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/cred/tid.rs",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["thread tracking"],
        },
        SyscallDef {
            name: "getuid",
            family: "process",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/cred/ids.rs",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["credential model"],
        },
        // CRITICAL_MEMORY (7)
        SyscallDef {
            name: "mmap",
            family: "memory",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/mmap_support.rs",
            issues: &[],
            tests: &["numeric_tests.rs", "fs_tests.rs"],
            dependencies: &["VFS", "page allocator", "CoW"],
        },
        SyscallDef {
            name: "munmap",
            family: "memory",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/posix/fs/mmap_support.rs",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["memory tracking"],
        },
        SyscallDef {
            name: "brk",
            family: "memory",
            status: SyscallStatus::Partial,
            location: "kernel/src/modules/linux_compat/mem/brk.rs",
            issues: &["sbrk-style return; heap growth bounded"],
            tests: &["linux_app_compat.rs"],
            dependencies: &["heap allocator"],
        },
        SyscallDef {
            name: "mprotect",
            family: "memory",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/mem/mman.rs:283",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["page protection", "CoW"],
        },
        SyscallDef {
            name: "madvise",
            family: "memory",
            status: SyscallStatus::Partial,
            location: "kernel/src/modules/linux_compat/mem/mman.rs:304",
            issues: &["hints only; enforcement limited"],
            tests: &["numeric_tests.rs"],
            dependencies: &["memory regions"],
        },
        SyscallDef {
            name: "mremap",
            family: "memory",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/mem/mman.rs:321",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["mmap infrastructure"],
        },
        SyscallDef {
            name: "remap_file_pages",
            family: "memory",
            status: SyscallStatus::Stub,
            location: "Only syscalls_consts/linux_numbers.rs:213",
            issues: &["NO dispatch; returns ENOSYS; deprecated since Linux 5.6"],
            tests: &[],
            dependencies: &["advanced VFS+mmap fusion"],
        },
        // CRITICAL_SIGNALS (6)
        SyscallDef {
            name: "rt_sigaction",
            family: "signals",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sig/action.rs:6",
            issues: &[],
            tests: &["sig/action.rs"],
            dependencies: &["signal delivery", "handlers"],
        },
        SyscallDef {
            name: "rt_sigprocmask",
            family: "signals",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sig/mask.rs:3",
            issues: &[],
            tests: &["sig/mask.rs"],
            dependencies: &["signal mask tracking"],
        },
        SyscallDef {
            name: "rt_sigpending",
            family: "signals",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sig/action.rs:44",
            issues: &[],
            tests: &["sig/action.rs"],
            dependencies: &["pending signal queue"],
        },
        SyscallDef {
            name: "rt_sigsuspend",
            family: "signals",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sig/mask.rs",
            issues: &[],
            tests: &["sig/mask.rs"],
            dependencies: &["scheduler", "signal delivery"],
        },
        SyscallDef {
            name: "sigaltstack",
            family: "signals",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sig/action.rs:99",
            issues: &[],
            tests: &["numeric_tests.rs", "sig/action.rs"],
            dependencies: &["stack allocation"],
        },
        SyscallDef {
            name: "rt_sigreturn",
            family: "signals",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sig/action.rs:58",
            issues: &[],
            tests: &["signal_frame_parity.rs"],
            dependencies: &["stack frame unwinding"],
        },
        // IMPORTANT_THREADING (5)
        SyscallDef {
            name: "futex",
            family: "threading",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sync/futex.rs:60",
            issues: &["supports 13 futex CMD variants"],
            tests: &["futex.rs"],
            dependencies: &["IPC backend", "wait queue"],
        },
        SyscallDef {
            name: "set_tid_address",
            family: "threading",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/cred/tid.rs",
            issues: &[],
            tests: &["numeric_tests.rs"],
            dependencies: &["thread identity", "clear_child_tid"],
        },
        SyscallDef {
            name: "set_robust_list",
            family: "threading",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sync/futex.rs:207",
            issues: &[],
            tests: &["futex.rs"],
            dependencies: &["robust futex infrastructure"],
        },
        SyscallDef {
            name: "clone3",
            family: "threading",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/sys/advanced/handlers/misc_kernel_apis.rs:195",
            issues: &[],
            tests: &["sys/advanced/mod.rs"],
            dependencies: &["clone infrastructure"],
        },
        SyscallDef {
            name: "exit_group",
            family: "threading",
            status: SyscallStatus::Full,
            location: "kernel/src/modules/linux_compat/process/lifecycle.rs",
            issues: &[],
            tests: &["p0_integration_harness.rs"],
            dependencies: &["process termination", "signal delivery"],
        },
    ]
}
