use core::sync::atomic::Ordering;

use super::{CoreRuntimeLimits, KernelConfig, *};

impl KernelConfig {
    pub fn runtime_limits() -> CoreRuntimeLimits {
        CoreRuntimeLimits {
            irq_vector_base: Self::irq_vector_base(),
            watchdog_hard_stall_ns: Self::watchdog_hard_stall_ns(),
            rt_force_reschedule_min_ticks: Self::rt_force_reschedule_min_ticks(),
            rt_deadline_burst_threshold: Self::rt_deadline_burst_threshold(),
            rebalance_prefer_local_skip_budget: Self::rebalance_prefer_local_skip_budget(),
            module_loader_max_load_segments: Self::module_loader_max_load_segments(),
            module_loader_max_total_image_bytes: Self::module_loader_max_total_image_bytes(),
            launch_max_process_name_len: Self::launch_max_process_name_len(),
            launch_max_boot_image_bytes: Self::launch_max_boot_image_bytes(),
            launch_handoff_stage_timeout_epochs: Self::launch_handoff_stage_timeout_epochs(),
            vfs_max_mounts: Self::vfs_max_mounts(),
            vfs_max_mount_path: Self::vfs_max_mount_path(),
            power_runqueue_saturation_limit: Self::power_runqueue_saturation_limit(),
            irqsafe_mutex_deadlock_spin_limit: Self::irqsafe_mutex_deadlock_spin_limit(),
            load_balance_percentile_window: Self::load_balance_percentile_window(),
        }
    }

    pub fn reset_runtime_overrides() {
        WATCHDOG_HARD_STALL_NS_OVERRIDE.store(0, Ordering::Relaxed);
        RT_FORCE_RESCHEDULE_MIN_TICKS_OVERRIDE.store(0, Ordering::Relaxed);
        RT_DEADLINE_BURST_THRESHOLD_OVERRIDE.store(0, Ordering::Relaxed);
        MODULE_LOADER_MAX_LOAD_SEGMENTS_OVERRIDE.store(0, Ordering::Relaxed);
        MODULE_LOADER_MAX_TOTAL_IMAGE_BYTES_OVERRIDE.store(0, Ordering::Relaxed);
        LAUNCH_MAX_PROCESS_NAME_LEN_OVERRIDE.store(0, Ordering::Relaxed);
        LAUNCH_MAX_BOOT_IMAGE_BYTES_OVERRIDE.store(0, Ordering::Relaxed);
        LAUNCH_STAGE_TIMEOUT_EPOCHS_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_MAX_MOUNTS_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_MAX_MOUNT_PATH_OVERRIDE.store(0, Ordering::Relaxed);
        IRQ_VECTOR_BASE_OVERRIDE.store(0, Ordering::Relaxed);
        POWER_RUNQUEUE_SATURATION_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        IRQSAFE_MUTEX_DEADLOCK_SPIN_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        DISKFS_MAX_PATH_LEN_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_ENABLE_BUFFERED_IO_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_HEALTH_SLO_MS_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_HEALTH_MAX_MOUNT_FAILURE_RATE_PER_MILLE_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_HEALTH_MAX_UNMOUNT_FAILURE_RATE_PER_MILLE_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_HEALTH_MAX_PATH_VALIDATION_FAILURES_OVERRIDE.store(0, Ordering::Relaxed);
        VFS_HEALTH_MAX_MOUNT_CAPACITY_PERCENT_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_DEFAULT_MODE_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_DEFAULT_UID_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_DEFAULT_GID_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_POLICY_PROFILE_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_NET_MODE_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_NET_GID_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_STORAGE_MODE_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_STORAGE_GID_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_ENABLE_HOTPLUG_NET_NODES_OVERRIDE.store(0, Ordering::Relaxed);
        DEVFS_ENABLE_HOTPLUG_STORAGE_NODES_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_POLL_INTERVAL_LOW_LATENCY_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_POLL_INTERVAL_BALANCED_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_POLL_INTERVAL_POWERSAVE_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_ADAPTIVE_QUEUE_DEPTH_DIVISOR_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_ADAPTIVE_HEALTH_LOW_THRESHOLD_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_ADAPTIVE_POLL_HIGH_THRESHOLD_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_RUNTIME_POLL_INTERVAL_MIN_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_EPOLL_MAX_EVENTS_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_EPOLL_MAX_FDS_PER_INSTANCE_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_LOOPBACK_QUEUE_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_UDP_QUEUE_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_TCP_QUEUE_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_FILTER_RULE_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_WIREGUARD_MAX_PEERS_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_HTTP_ASSET_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_SLO_SAMPLE_INTERVAL_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_SLO_LOG_INTERVAL_MULTIPLIER_OVERRIDE.store(0, Ordering::Relaxed);
        NETWORK_TLS_POLICY_PROFILE_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_POSIX_FD_START_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_POSIX_EPHEMERAL_START_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_POSIX_BLOCKING_RECV_RETRIES_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_IRQ_SERVICE_BUDGET_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_LOOP_SERVICE_BUDGET_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_RING_LIMIT_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_QUARANTINE_REBIND_FAILURES_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_QUARANTINE_COOLDOWN_SAMPLES_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_SLO_MAX_DROP_RATE_PER_MILLE_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_SLO_MAX_TX_RING_UTILIZATION_PERCENT_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_SLO_MAX_RX_RING_UTILIZATION_PERCENT_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_SLO_MAX_IO_ERRORS_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_LOW_LATENCY_IRQ_BUDGET_DIVISOR_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_LOW_LATENCY_LOOP_BUDGET_DIVISOR_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_LOW_LATENCY_RING_LIMIT_DIVISOR_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_THROUGHPUT_IRQ_BUDGET_MULTIPLIER_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_THROUGHPUT_LOOP_BUDGET_MULTIPLIER_OVERRIDE.store(0, Ordering::Relaxed);
        DRIVER_NETWORK_THROUGHPUT_RING_LIMIT_MULTIPLIER_OVERRIDE.store(0, Ordering::Relaxed);
        AHCI_IO_TIMEOUT_SPINS_OVERRIDE.store(0, Ordering::Relaxed);
        NVME_DISABLE_READY_TIMEOUT_SPINS_OVERRIDE.store(0, Ordering::Relaxed);
        NVME_POLL_TIMEOUT_SPINS_OVERRIDE.store(0, Ordering::Relaxed);
        NVME_IO_TIMEOUT_SPINS_OVERRIDE.store(0, Ordering::Relaxed);
        E1000_RESET_TIMEOUT_SPINS_OVERRIDE.store(0, Ordering::Relaxed);
        E1000_BUFFER_SIZE_BYTES_OVERRIDE.store(0, Ordering::Relaxed);
        E1000_RX_DESC_COUNT_OVERRIDE.store(0, Ordering::Relaxed);
        E1000_TX_DESC_COUNT_OVERRIDE.store(0, Ordering::Relaxed);
        RUNTIME_POLICY_DRIFT_SAMPLE_INTERVAL_TICKS_OVERRIDE.store(0, Ordering::Relaxed);
        RUNTIME_POLICY_DRIFT_REAPPLY_COOLDOWN_TICKS_OVERRIDE.store(0, Ordering::Relaxed);
        SYSCALL_MAX_PATH_LEN_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_LOTTERY_INITIAL_SEED_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_LOTTERY_TICKETS_PER_PRIORITY_LEVEL_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_LOTTERY_MIN_TICKETS_PER_TASK_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_LOTTERY_LCG_MULTIPLIER_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_LOTTERY_LCG_INCREMENT_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_CFS_MIN_GRANULARITY_NS_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_CFS_LATENCY_TARGET_NS_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_MLFQ_BASE_SLICE_NS_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_MLFQ_BOOST_INTERVAL_TICKS_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_MLFQ_DEMOTE_ON_SLICE_EXHAUSTION_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_EDF_ENFORCE_DEADLINE_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_EDF_DEFAULT_RELATIVE_DEADLINE_NS_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_RT_ENABLE_GROUP_RESERVATION_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_RT_PERIOD_NS_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_RT_TOTAL_UTILIZATION_CAP_PERCENT_OVERRIDE.store(0, Ordering::Relaxed);
        SCHED_RT_MAX_GROUPS_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_RUNTIME_SUMMARY_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_VIRTUALIZATION_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_PLATFORM_LIFECYCLE_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_ENTRY_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_RESUME_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_TRAP_DISPATCH_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_NESTED_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_TIME_VIRTUALIZATION_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_DEVICE_PASSTHROUGH_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_SNAPSHOT_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_DIRTY_LOGGING_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_LIVE_MIGRATION_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_TRAP_TRACING_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_EXECUTION_CLASS_OVERRIDE.store(0, Ordering::Relaxed);
        VIRTUALIZATION_GOVERNOR_CLASS_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_VFS_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_NETWORK_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_IPC_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_SCHEDULER_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_SECURITY_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_POWER_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_DRIVERS_OVERRIDE.store(0, Ordering::Relaxed);
        DEBUG_TRACE_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        SERIAL_EARLY_DEBUG_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        // Reset granular category-level observability overrides
        OBSERVABILITY_CORE_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_BOOT_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_LOADER_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_TASK_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_MEMORY_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_SCHEDULER_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_FAULT_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_DRIVER_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_IO_OVERRIDE.store(0, Ordering::Relaxed);
        OBSERVABILITY_NETWORK_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_HISTORY_LEN_OVERRIDE.store(0, Ordering::Relaxed);
        TELEMETRY_LOG_LEVEL_NUM_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_BOUNDARY_MODE_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_ENFORCE_CORE_MINIMAL_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_STRICT_OPTIONAL_FEATURES_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_EXPOSE_VFS_API_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_EXPOSE_NETWORK_API_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_EXPOSE_IPC_API_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_EXPOSE_PROC_CONFIG_API_OVERRIDE.store(0, Ordering::Relaxed);
        LIBRARY_EXPOSE_SYSCTL_API_OVERRIDE.store(0, Ordering::Relaxed);
        EXEC_ELF_REQUIRE_ABSOLUTE_INTERP_PATH_OVERRIDE.store(0, Ordering::Relaxed);
        EXEC_ELF_ENFORCE_INTERP_PATH_SANITIZATION_OVERRIDE.store(0, Ordering::Relaxed);
        EXEC_ELF_ENFORCE_SYSTEM_LOADER_PATHS_OVERRIDE.store(0, Ordering::Relaxed);
        EXEC_ELF_ENFORCE_SEGMENT_CONGRUENCE_OVERRIDE.store(0, Ordering::Relaxed);
        EXEC_AUXV_ENFORCE_HANDOFF_CONTRACT_OVERRIDE.store(0, Ordering::Relaxed);
        EXEC_AUXV_REQUIRE_PHDR_TRIPLET_OVERRIDE.store(0, Ordering::Relaxed);
        USERSPACE_ABI_REQUIRE_GLIBC_VFS_SURFACE_OVERRIDE.store(0, Ordering::Relaxed);
        USERSPACE_ABI_REQUIRE_GLIBC_NETWORK_SURFACE_OVERRIDE.store(0, Ordering::Relaxed);
        USERSPACE_ABI_REQUIRE_GLIBC_IPC_SURFACE_OVERRIDE.store(0, Ordering::Relaxed);
        USERSPACE_ABI_LIBC_SURFACE_WEIGHT_PERCENT_OVERRIDE.store(0, Ordering::Relaxed);
        SECURITY_ENFORCEMENT_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        CAPABILITY_ENFORCEMENT_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        MULTI_USER_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        CREDENTIAL_ENFORCEMENT_ENABLED_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_FAST_PATH_RUN_PUMP_OVERRIDE.store(0, Ordering::Relaxed);
        LIBNET_FAST_PATH_COLLECT_TRANSPORT_SNAPSHOT_OVERRIDE.store(0, Ordering::Relaxed);
    }
}
