use super::super::*;
use super::SyscallDispFrame;
use crate::hal::syscalls_consts::linux_nr;

pub fn dispatch_fs(nr: usize, f: &mut SyscallDispFrame) -> Option<usize> {
    match nr {
        linux_nr::ACCESS => Some(sys_linux_access(f.u1(), f.a2)),
        linux_nr::CHMOD => Some(sys_linux_chmod(f.u1(), f.a2)),
        linux_nr::CHOWN => Some(sys_linux_chown(f.u1(), f.a2, f.a3)),
        linux_nr::CHDIR => Some(sys_linux_chdir(f.u1())),
        linux_nr::CHROOT => Some(sys_linux_chroot(f.u1())),
        linux_nr::CLOSE_RANGE => Some(crate::modules::linux_compat::fs::sys_linux_close_range(
            f.a1, f.a2, f.a3,
        )),
        linux_nr::COPY_FILE_RANGE => {
            Some(crate::modules::linux_compat::fs::sys_linux_copy_file_range(
                f.fd1(),
                f.u2(),
                f.fd3(),
                f.u4(),
                f.a5,
                f.a6,
            ))
        }
        linux_nr::DUP3 => Some(crate::modules::linux_compat::fs::sys_linux_dup3(
            f.fd1(),
            f.fd2(),
            f.a3,
        )),
        linux_nr::FACCESSAT => Some(sys_linux_faccessat(f.fd1(), f.u2(), f.a3, 0)),
        linux_nr::FACCESSAT2 => Some(sys_linux_faccessat2(f.fd1(), f.u2(), f.a3, f.a4)),
        linux_nr::FALLOCATE => Some(crate::modules::linux_compat::fs::sys_linux_fallocate(
            f.fd1(),
            f.a2,
            f.a3,
            f.a4,
        )),
        linux_nr::FCHDIR => Some(crate::modules::linux_compat::fs::sys_linux_fchdir(f.fd1())),
        linux_nr::FCHMOD => Some(sys_linux_fchmod(f.fd1(), f.a2)),
        linux_nr::FCHMODAT => Some(sys_linux_fchmodat(f.fd1(), f.u2(), f.a3, f.a4)),
        linux_nr::FCHOWN => Some(sys_linux_fchown(f.fd1(), f.a2, f.a3)),
        linux_nr::FCHOWNAT => Some(sys_linux_fchownat(f.fd1(), f.u2(), f.a3, f.a4, f.a5)),
        linux_nr::FCNTL => Some(sys_linux_fcntl(f.fd1(), f.a2, f.a3)),
        linux_nr::FDATASYNC => Some(crate::modules::linux_compat::fs::sys_linux_fdatasync(
            f.fd1(),
        )),
        linux_nr::FGETXATTR => Some(sys_linux_fgetxattr(f.fd1(), f.u2(), f.u3(), f.a4)),
        linux_nr::FLISTXATTR => Some(sys_linux_flistxattr(f.fd1(), f.u2(), f.a3)),
        linux_nr::FREMOVEXATTR => Some(sys_linux_fremovexattr(f.fd1(), f.u2())),
        linux_nr::FSETXATTR => Some(sys_linux_fsetxattr(f.fd1(), f.u2(), f.u3(), f.a4, f.a5)),
        linux_nr::FSTAT => Some(sys_linux_fstat(f.fd1(), f.u2())),
        linux_nr::NEWFSTATAT => Some(sys_linux_newfstatat(f.fd1(), f.u2(), f.u3(), f.a4)),
        linux_nr::FSTATFS => Some(sys_linux_fstatfs(f.fd1(), f.u2())),
        linux_nr::FSYNC => Some(sys_linux_fsync(f.fd1())),
        linux_nr::FTRUNCATE => Some(sys_linux_ftruncate(f.fd1(), f.a2)),
        linux_nr::GETCWD => Some(sys_linux_getcwd(f.u1(), f.a2)),
        linux_nr::GETDENTS => Some(sys_linux_getdents64(f.fd1(), f.u2(), f.a3)),
        linux_nr::GETDENTS64 => Some(sys_linux_getdents64(f.fd1(), f.u2(), f.a3)),
        linux_nr::GETXATTR => Some(sys_linux_getxattr(f.u1(), f.u2(), f.u3(), f.a4)),
        linux_nr::INOTIFY_INIT => Some(sys_linux_inotify_init()),
        linux_nr::INOTIFY_INIT1 => Some(sys_linux_inotify_init1(f.a1 as i32)),
        linux_nr::INOTIFY_ADD_WATCH => {
            Some(sys_linux_inotify_add_watch(f.fd1(), f.u2(), f.a3 as u32))
        }
        linux_nr::INOTIFY_RM_WATCH => Some(sys_linux_inotify_rm_watch(f.fd1(), f.a2 as i32)),
        linux_nr::IOCTL => Some(sys_linux_ioctl(f.fd1(), f.a2, f.a3)),
        linux_nr::LCHOWN => Some(crate::modules::linux_compat::fs::sys_linux_lchown(
            f.u1(),
            f.a2,
            f.a3,
        )),
        linux_nr::LGETXATTR => Some(sys_linux_lgetxattr(f.u1(), f.u2(), f.u3(), f.a4)),
        linux_nr::LINKAT => Some(sys_linux_linkat(f.fd1(), f.u2(), f.fd3(), f.u4(), f.a5)),
        linux_nr::LISTXATTR => Some(sys_linux_listxattr(f.u1(), f.u2(), f.a3)),
        linux_nr::LLISTXATTR => Some(sys_linux_llistxattr(f.u1(), f.u2(), f.a3)),
        linux_nr::LREMOVEXATTR => Some(sys_linux_lremovexattr(f.u1(), f.u2())),
        linux_nr::LSEEK => Some(sys_linux_lseek(f.fd1(), f.a2 as i64, f.a3)),
        linux_nr::LSETXATTR => Some(sys_linux_lsetxattr(f.u1(), f.u2(), f.u3(), f.a4, f.a5)),
        linux_nr::LSTAT => Some(sys_linux_lstat(f.u1(), f.u2())),
        linux_nr::MKDIR => Some(sys_linux_mkdir(f.u1(), f.a2)),
        linux_nr::MKDIRAT => Some(sys_linux_mkdirat(f.fd1(), f.u2(), f.a3)),
        linux_nr::MKNOD => Some(sys_linux_mknod(f.u1(), f.a2, f.a3)),
        linux_nr::MKNODAT => Some(sys_linux_mknodat(f.fd1(), f.u2(), f.a3, f.a4)),
        linux_nr::OPENAT => Some(sys_linux_openat(f.fd1(), f.u2(), f.a3, f.a4)),
        linux_nr::OPENAT2 => Some(sys_linux_openat2(f.fd1(), f.u2(), f.u3(), f.a4)),
        linux_nr::PIPE => Some(crate::modules::linux_compat::fs::sys_linux_pipe(f.u1())),
        linux_nr::PIPE2 => Some(crate::modules::linux_compat::fs::sys_linux_pipe2(
            f.u1(),
            f.a2,
        )),
        linux_nr::PIVOT_ROOT => Some(sys_linux_pivot_root(f.u1(), f.u2())),
        linux_nr::PREAD64 => Some(sys_linux_pread64(f.fd1(), f.u2(), f.a3, f.a4)),
        linux_nr::PWRITE64 => Some(sys_linux_pwrite64(f.fd1(), f.u2(), f.a3, f.a4)),
        linux_nr::READLINK => Some(sys_linux_readlink(f.u1(), f.u2(), f.a3)),
        linux_nr::READLINKAT => Some(sys_linux_readlinkat(f.fd1(), f.u2(), f.u3(), f.a4)),
        linux_nr::READV => Some(sys_linux_readv(f.fd1(), f.u2(), f.a3)),
        linux_nr::REMOVEXATTR => Some(sys_linux_removexattr(f.u1(), f.u2())),
        linux_nr::RENAME => Some(sys_linux_rename(f.u1(), f.u2())),
        linux_nr::RENAMEAT => Some(sys_linux_renameat(f.fd1(), f.u2(), f.fd3(), f.u4())),
        linux_nr::RENAMEAT2 => Some(sys_linux_renameat2(f.fd1(), f.u2(), f.fd3(), f.u4(), f.a5)),
        linux_nr::RMDIR => Some(sys_linux_rmdir(f.u1())),
        linux_nr::SETXATTR => Some(sys_linux_setxattr(f.u1(), f.u2(), f.u3(), f.a4, f.a5)),
        linux_nr::SYMLINK => Some(sys_linux_symlink(f.u1(), f.u2())),
        linux_nr::SYMLINKAT => Some(sys_linux_symlinkat(f.u1(), f.fd2(), f.u3())),
        linux_nr::STAT => Some(sys_linux_stat(f.u1(), f.u2())),
        linux_nr::STATFS => Some(sys_linux_statfs(f.u1(), f.u2())),
        linux_nr::STATX => Some(sys_linux_statx(f.fd1(), f.u2(), f.a3, f.a4, f.u5())),
        linux_nr::SYNC => Some(crate::modules::linux_compat::fs::sys_linux_sync()),
        linux_nr::SYNCFS => Some(crate::modules::linux_compat::fs::sys_linux_syncfs(f.fd1())),
        linux_nr::TRUNCATE => Some(sys_linux_truncate(f.u1(), f.a2)),
        linux_nr::UMASK => Some(sys_linux_umask(f.a1)),
        linux_nr::UNLINK => Some(sys_linux_unlink(f.u1())),
        linux_nr::UNLINKAT => Some(sys_linux_unlinkat(f.fd1(), f.u2(), f.a3)),
        linux_nr::UTIME => Some(sys_linux_utime(f.u1(), f.u2())),
        linux_nr::UTIMENSAT => Some(sys_linux_utimensat(f.fd1(), f.u2(), f.u3(), f.a4)),
        linux_nr::WRITEV => Some(sys_linux_writev(f.fd1(), f.u2(), f.a3)),
        linux_nr::SENDFILE => Some(crate::modules::linux_compat::fs::sys_linux_sendfile(
            f.fd1(),
            f.fd2(),
            f.u3(),
            f.a4,
        )),
        linux_nr::SPLICE => Some(crate::modules::linux_compat::fs::sys_linux_splice(
            f.fd1(),
            f.u2(),
            f.fd3(),
            f.u4(),
            f.a5,
            f.a6,
        )),
        linux_nr::TEE => Some(crate::modules::linux_compat::fs::sys_linux_tee(
            f.fd1(),
            f.fd2(),
            f.a3,
            f.a4,
        )),
        linux_nr::VMSPLICE => Some(crate::modules::linux_compat::fs::sys_linux_vmsplice(
            f.fd1(),
            f.u2(),
            f.a3,
            f.a4,
        )),

        // ── Modern Mount APIs ────────────────────────────────────────────────
        linux_nr::FSOPEN => Some(sys_linux_fsopen(f.u1(), f.a2)),
        linux_nr::FSMOUNT => Some(sys_linux_fsmount(f.fd1(), f.a2, f.a3)),
        linux_nr::FSPICK => Some(sys_linux_fspick(f.fd1(), f.u2(), f.a3)),
        linux_nr::MOVE_MOUNT => Some(sys_linux_move_mount(f.fd1(), f.u2(), f.fd3(), f.u4(), f.a5)),
        linux_nr::OPEN_TREE => Some(sys_linux_open_tree(f.fd1(), f.u2(), f.a3)),
        linux_nr::MOUNT_SETATTR => Some(sys_linux_mount_setattr(
            f.fd1(),
            f.u2(),
            f.a3,
            f.u4::<u8>().cast(),
            f.a5,
        )),
        linux_nr::MOUNT => Some(sys_linux_mount(f.u1(), f.u2(), f.u3(), f.a4, f.u5())),
        linux_nr::UMOUNT2 => Some(sys_linux_umount2(f.u1(), f.a2)),

        _ => None,
    }
}
