use super::*;

#[derive(Debug, Clone, Copy)]
pub struct SyscallStats {
    pub total: u64,
    pub unknown: u64,
    pub invalid_args: u64,
    pub user_access_denied: u64,
    pub user_word_unaligned_denied: u64,
    pub print_calls: u64,
    pub tls_calls: u64,
    pub affinity_calls: u64,
    pub abi_info_calls: u64,
    pub launch_stats_calls: u64,
    pub process_count_calls: u64,
    pub process_list_calls: u64,
    pub process_spawn_calls: u64,
    pub process_image_state_calls: u64,
    pub process_mapping_state_calls: u64,
    pub vfs_mount_ramfs_calls: u64,
    pub vfs_list_mounts_calls: u64,
    pub power_stats_calls: u64,
    pub power_override_set_calls: u64,
    pub power_override_clear_calls: u64,
    pub network_stats_calls: u64,
    pub network_poll_control_calls: u64,
    pub process_terminate_calls: u64,
    pub process_launch_ctx_calls: u64,
    pub vfs_mount_path_calls: u64,
    pub vfs_unmount_calls: u64,
    pub vfs_stats_calls: u64,
    pub network_reset_stats_calls: u64,
    pub network_force_poll_calls: u64,
    pub power_cstate_set_calls: u64,
    pub power_cstate_clear_calls: u64,
    pub process_claim_ctx_calls: u64,
    pub process_ack_ctx_calls: u64,
    pub process_ctx_stage_calls: u64,
    pub task_terminate_calls: u64,
    pub task_process_id_calls: u64,
    pub vfs_unmount_path_calls: u64,
    pub network_reinit_calls: u64,
    pub process_consume_ctx_calls: u64,
    pub process_execute_ctx_calls: u64,
    pub futex_wait_calls: u64,
    pub futex_wake_calls: u64,
    pub upcall_register_calls: u64,
    pub upcall_unregister_calls: u64,
    pub upcall_query_calls: u64,
    pub upcall_consume_calls: u64,
    pub upcall_inject_virq_calls: u64,
    pub network_backpressure_policy_calls: u64,
    pub network_alert_thresholds_calls: u64,
    pub network_alert_report_calls: u64,
    pub crash_report_calls: u64,
    pub crash_events_calls: u64,
    pub core_pressure_snapshot_calls: u64,
    pub lottery_replay_latest_calls: u64,
    pub policy_drift_control_set_calls: u64,
    pub policy_drift_control_get_calls: u64,
    pub policy_drift_reason_text_calls: u64,
}

pub fn stats() -> SyscallStats {
    SyscallStats {
        total: SYSCALL_TOTAL.load(Ordering::Relaxed),
        unknown: SYSCALL_UNKNOWN.load(Ordering::Relaxed),
        invalid_args: SYSCALL_INVALID_ARGS.load(Ordering::Relaxed),
        user_access_denied: SYSCALL_USER_ACCESS_DENIED.load(Ordering::Relaxed),
        user_word_unaligned_denied: SYSCALL_USER_WORD_UNALIGNED_DENIED.load(Ordering::Relaxed),
        print_calls: SYSCALL_PRINT_CALLS.load(Ordering::Relaxed),
        tls_calls: SYSCALL_TLS_CALLS.load(Ordering::Relaxed),
        affinity_calls: SYSCALL_AFFINITY_CALLS.load(Ordering::Relaxed),
        abi_info_calls: SYSCALL_ABI_INFO_CALLS.load(Ordering::Relaxed),
        launch_stats_calls: SYSCALL_LAUNCH_STATS_CALLS.load(Ordering::Relaxed),
        process_count_calls: SYSCALL_PROCESS_COUNT_CALLS.load(Ordering::Relaxed),
        process_list_calls: SYSCALL_PROCESS_LIST_CALLS.load(Ordering::Relaxed),
        process_spawn_calls: SYSCALL_PROCESS_SPAWN_CALLS.load(Ordering::Relaxed),
        process_image_state_calls: SYSCALL_PROCESS_IMAGE_STATE_CALLS.load(Ordering::Relaxed),
        process_mapping_state_calls: SYSCALL_PROCESS_MAPPING_STATE_CALLS.load(Ordering::Relaxed),
        vfs_mount_ramfs_calls: SYSCALL_VFS_MOUNT_RAMFS_CALLS.load(Ordering::Relaxed),
        vfs_list_mounts_calls: SYSCALL_VFS_LIST_MOUNTS_CALLS.load(Ordering::Relaxed),
        power_stats_calls: SYSCALL_POWER_STATS_CALLS.load(Ordering::Relaxed),
        power_override_set_calls: SYSCALL_POWER_OVERRIDE_SET_CALLS.load(Ordering::Relaxed),
        power_override_clear_calls: SYSCALL_POWER_OVERRIDE_CLEAR_CALLS.load(Ordering::Relaxed),
        network_stats_calls: SYSCALL_NETWORK_STATS_CALLS.load(Ordering::Relaxed),
        network_poll_control_calls: SYSCALL_NETWORK_POLL_CONTROL_CALLS.load(Ordering::Relaxed),
        process_terminate_calls: SYSCALL_PROCESS_TERMINATE_CALLS.load(Ordering::Relaxed),
        process_launch_ctx_calls: SYSCALL_PROCESS_LAUNCH_CTX_CALLS.load(Ordering::Relaxed),
        vfs_mount_path_calls: SYSCALL_VFS_MOUNT_PATH_CALLS.load(Ordering::Relaxed),
        vfs_unmount_calls: SYSCALL_VFS_UNMOUNT_CALLS.load(Ordering::Relaxed),
        vfs_stats_calls: SYSCALL_VFS_STATS_CALLS.load(Ordering::Relaxed),
        network_reset_stats_calls: SYSCALL_NETWORK_RESET_STATS_CALLS.load(Ordering::Relaxed),
        network_force_poll_calls: SYSCALL_NETWORK_FORCE_POLL_CALLS.load(Ordering::Relaxed),
        power_cstate_set_calls: SYSCALL_POWER_CSTATE_SET_CALLS.load(Ordering::Relaxed),
        power_cstate_clear_calls: SYSCALL_POWER_CSTATE_CLEAR_CALLS.load(Ordering::Relaxed),
        process_claim_ctx_calls: SYSCALL_PROCESS_CLAIM_CTX_CALLS.load(Ordering::Relaxed),
        process_ack_ctx_calls: SYSCALL_PROCESS_ACK_CTX_CALLS.load(Ordering::Relaxed),
        process_ctx_stage_calls: SYSCALL_PROCESS_CTX_STAGE_CALLS.load(Ordering::Relaxed),
        task_terminate_calls: SYSCALL_TASK_TERMINATE_CALLS.load(Ordering::Relaxed),
        task_process_id_calls: SYSCALL_TASK_PROCESS_ID_CALLS.load(Ordering::Relaxed),
        vfs_unmount_path_calls: SYSCALL_VFS_UNMOUNT_PATH_CALLS.load(Ordering::Relaxed),
        network_reinit_calls: SYSCALL_NETWORK_REINIT_CALLS.load(Ordering::Relaxed),
        process_consume_ctx_calls: SYSCALL_PROCESS_CONSUME_CTX_CALLS.load(Ordering::Relaxed),
        process_execute_ctx_calls: SYSCALL_PROCESS_EXECUTE_CTX_CALLS.load(Ordering::Relaxed),
        futex_wait_calls: SYSCALL_FUTEX_WAIT_CALLS.load(Ordering::Relaxed),
        futex_wake_calls: SYSCALL_FUTEX_WAKE_CALLS.load(Ordering::Relaxed),
        upcall_register_calls: SYSCALL_UPCALL_REGISTER_CALLS.load(Ordering::Relaxed),
        upcall_unregister_calls: SYSCALL_UPCALL_UNREGISTER_CALLS.load(Ordering::Relaxed),
        upcall_query_calls: SYSCALL_UPCALL_QUERY_CALLS.load(Ordering::Relaxed),
        upcall_consume_calls: SYSCALL_UPCALL_CONSUME_CALLS.load(Ordering::Relaxed),
        upcall_inject_virq_calls: SYSCALL_UPCALL_INJECT_VIRQ_CALLS.load(Ordering::Relaxed),
        network_backpressure_policy_calls: SYSCALL_NETWORK_BACKPRESSURE_POLICY_CALLS
            .load(Ordering::Relaxed),
        network_alert_thresholds_calls: SYSCALL_NETWORK_ALERT_THRESHOLDS_CALLS
            .load(Ordering::Relaxed),
        network_alert_report_calls: SYSCALL_NETWORK_ALERT_REPORT_CALLS.load(Ordering::Relaxed),
        crash_report_calls: SYSCALL_CRASH_REPORT_CALLS.load(Ordering::Relaxed),
        crash_events_calls: SYSCALL_CRASH_EVENTS_CALLS.load(Ordering::Relaxed),
        core_pressure_snapshot_calls: SYSCALL_CORE_PRESSURE_SNAPSHOT_CALLS.load(Ordering::Relaxed),
        lottery_replay_latest_calls: SYSCALL_LOTTERY_REPLAY_LATEST_CALLS.load(Ordering::Relaxed),
        policy_drift_control_set_calls: SYSCALL_POLICY_DRIFT_CONTROL_SET_CALLS
            .load(Ordering::Relaxed),
        policy_drift_control_get_calls: SYSCALL_POLICY_DRIFT_CONTROL_GET_CALLS
            .load(Ordering::Relaxed),
        policy_drift_reason_text_calls: SYSCALL_POLICY_DRIFT_REASON_TEXT_CALLS
            .load(Ordering::Relaxed),
    }
}
