#[derive(Debug, Clone, Copy)]
pub struct NetworkBridgeStats {
    pub smoltcp_bridge_inits: u64,
    pub smoltcp_polls: u64,
    pub smoltcp_rx_frames: u64,
    pub smoltcp_tx_frames: u64,
    pub smoltcp_runtime_ready: bool,
    pub smoltcp_runtime_poll_enabled: bool,
    pub smoltcp_init_errors: u64,
    pub smoltcp_poll_errors: u64,
    pub smoltcp_poll_skips: u64,
    pub smoltcp_runtime_control_updates: u64,
    pub smoltcp_poll_interval_ticks: u64,
    pub smoltcp_force_polls: u64,
    pub smoltcp_reinitialize_calls: u64,
    pub smoltcp_health_score: u64,
    pub backpressure_drop_actions: u64,
    pub backpressure_defer_actions: u64,
    pub backpressure_force_poll_actions: u64,
    pub loopback_backpressure_policy: u64,
    #[cfg(feature = "network_transport")]
    pub udp_backpressure_policy: u64,
    #[cfg(feature = "network_transport")]
    pub tcp_backpressure_policy: u64,
    pub loopback_send_calls: u64,
    pub loopback_send_drops: u64,
    pub loopback_receive_calls: u64,
    pub loopback_receive_hits: u64,
    pub loopback_queue_high_water: u64,
    pub udp_bind_calls: u64,
    pub udp_send_calls: u64,
    pub udp_send_drops: u64,
    pub udp_recv_calls: u64,
    pub udp_recv_hits: u64,
    pub udp_queue_high_water: u64,
    pub tcp_listen_calls: u64,
    pub tcp_connect_calls: u64,
    pub tcp_accept_calls: u64,
    pub tcp_accept_hits: u64,
    pub tcp_send_calls: u64,
    pub tcp_send_drops: u64,
    pub udp_send_latency_p50_ticks: u64,
    pub udp_send_latency_p95_ticks: u64,
    pub udp_send_latency_p99_ticks: u64,
    pub udp_recv_latency_p50_ticks: u64,
    pub udp_recv_latency_p95_ticks: u64,
    pub udp_recv_latency_p99_ticks: u64,
    pub tcp_send_latency_p50_ticks: u64,
    pub tcp_send_latency_p95_ticks: u64,
    pub tcp_send_latency_p99_ticks: u64,
    pub tcp_recv_latency_p50_ticks: u64,
    pub tcp_recv_latency_p95_ticks: u64,
    pub tcp_recv_latency_p99_ticks: u64,
    pub tcp_recv_calls: u64,
    pub tcp_recv_hits: u64,
    pub tcp_queue_high_water: u64,
    pub dns_register_calls: u64,
    pub dns_resolve_calls: u64,
    pub dns_resolve_hits: u64,
    pub filter_register_calls: u64,
    pub filter_remove_calls: u64,
    pub filter_clear_calls: u64,
    pub filter_eval_calls: u64,
    pub filter_eval_allow: u64,
    pub filter_eval_drop: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_add_peer_calls: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_remove_peer_calls: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_encap_calls: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_decap_calls: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_drop_calls: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_bytes_encap: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_bytes_decap: u64,
    #[cfg(feature = "network_wireguard")]
    pub wg_active_peers_high_water: u64,
    #[cfg(feature = "network_http")]
    pub http_register_calls: u64,
    #[cfg(feature = "network_http")]
    pub http_remove_calls: u64,
    #[cfg(feature = "network_http")]
    pub http_request_calls: u64,
    #[cfg(feature = "network_http")]
    pub http_resp_200: u64,
    #[cfg(feature = "network_http")]
    pub http_resp_304: u64,
    #[cfg(feature = "network_http")]
    pub http_resp_404: u64,
    #[cfg(feature = "network_http")]
    pub http_sendfile_calls: u64,
    #[cfg(feature = "network_http")]
    pub http_bytes_served: u64,
}