use crate::modules::linux_compat::*;

pub(super) fn dispatch_linux_advanced_syscall(
    frame: &mut SyscallFrame,
    syscall_id: usize,
    arg1: usize,
    arg2: usize,
    arg3: usize,
    arg4: usize,
    arg5: usize,
    arg6: usize,
) -> Option<usize> {
    match syscall_id {
        linux_nr::FSOPEN => Some(sys_linux_fsopen(UserPtr::new(arg1), arg2)),
        linux_nr::FSMOUNT => Some(sys_linux_fsmount(Fd::from(arg1), arg2, arg3)),
        linux_nr::FSPICK => Some(sys_linux_fspick(Fd::from(arg1), UserPtr::new(arg2), arg3)),
        linux_nr::MOVE_MOUNT => Some(sys_linux_move_mount(
            Fd::from(arg1),
            UserPtr::new(arg2),
            Fd::from(arg3),
            UserPtr::new(arg4),
            arg5,
        )),
        linux_nr::CAPGET => Some(sys_linux_capget(UserPtr::new(arg1), UserPtr::new(arg2))),
        linux_nr::CAPSET => Some(sys_linux_capset(UserPtr::new(arg1), UserPtr::new(arg2))),
        linux_nr::RT_SIGQUEUEINFO => {
            Some(sys_linux_rt_sigqueueinfo(arg1, arg2, UserPtr::new(arg3)))
        }
        linux_nr::SYSFS => Some(sys_linux_sysfs(arg1, arg2, arg3)),
        linux_nr::SYSCTL => Some(sys_linux_sysctl(UserPtr::new(arg1))),
        linux_nr::VHANGUP => Some(sys_linux_vhangup()),
        linux_nr::ACCT => Some(sys_linux_acct(UserPtr::new(arg1))),
        linux_nr::REBOOT => Some(sys_linux_reboot(arg1, arg2, arg3, arg4)),
        linux_nr::IOPL => Some(sys_linux_iopl(arg1)),
        linux_nr::IOPERM => Some(sys_linux_ioperm(arg1, arg2, arg3)),
        linux_nr::CREATE_MODULE => Some(sys_linux_create_module(UserPtr::new(arg1), arg2)),
        linux_nr::INIT_MODULE => Some(sys_linux_init_module(
            UserPtr::new(arg1),
            arg2,
            UserPtr::new(arg3),
        )),
        linux_nr::DELETE_MODULE => Some(sys_linux_delete_module(UserPtr::new(arg1), arg2)),
        linux_nr::SECURITY => Some(sys_linux_security(arg1, arg2, arg3, arg4)),
        linux_nr::TIMER_CREATE => Some(sys_linux_timer_create(
            arg1,
            UserPtr::new(arg2),
            UserPtr::new(arg3),
        )),
        linux_nr::TIMER_DELETE => Some(sys_linux_timer_delete(arg1)),
        linux_nr::OPEN_BY_HANDLE_AT => Some(sys_linux_open_by_handle_at(
            Fd::from(arg1),
            UserPtr::new(arg2),
            arg3,
        )),
        linux_nr::MEMFD_CREATE => Some(sys_linux_memfd_create(UserPtr::new(arg1), arg2)),
        linux_nr::KEXEC_FILE_LOAD => Some(sys_linux_kexec_file_load(
            Fd::from(arg1),
            Fd::from(arg2),
            arg3,
            UserPtr::new(arg4),
            arg5,
        )),
        linux_nr::BPF => Some(sys_linux_bpf(arg1, UserPtr::new(arg2), arg3)),
        linux_nr::EXECVEAT => Some(sys_linux_execveat(
            frame,
            Fd::from(arg1),
            arg2,
            arg3,
            arg4,
            arg5,
        )),
        linux_nr::USERFAULTFD => Some(sys_linux_userfaultfd(arg1)),
        linux_nr::MEMBARRIER => Some(sys_linux_membarrier(arg1, arg2, arg3)),
        linux_nr::MLOCK2 => Some(sys_linux_mlock2(UserPtr::new(arg1), arg2, arg3)),
        linux_nr::COPY_FILE_RANGE => {
            Some(crate::modules::linux_compat::fs::sys_linux_copy_file_range(
                Fd::from(arg1),
                UserPtr::new(arg2),
                Fd::from(arg3),
                UserPtr::new(arg4),
                arg5,
                arg6,
            ))
        }
        linux_nr::PREADV2 => Some(sys_linux_preadv2(
            Fd::from(arg1),
            UserPtr::new(arg2),
            arg3,
            arg4,
            arg5,
        )),
        linux_nr::PREADV => Some(sys_linux_preadv(
            Fd::from(arg1),
            UserPtr::new(arg2),
            arg3,
            arg4,
            arg5,
        )),
        linux_nr::PWRITEV2 => Some(sys_linux_pwritev2(
            Fd::from(arg1),
            UserPtr::new(arg2),
            arg3,
            arg4,
            arg5,
        )),
        linux_nr::PWRITEV => Some(sys_linux_pwritev(
            Fd::from(arg1),
            UserPtr::new(arg2),
            arg3,
            arg4,
            arg5,
        )),
        linux_nr::PKEY_MPROTECT => Some(sys_linux_pkey_mprotect(
            UserPtr::new(arg1),
            arg2,
            arg3,
            arg4,
        )),
        linux_nr::PKEY_ALLOC => Some(sys_linux_pkey_alloc(arg1, arg2)),
        linux_nr::PKEY_FREE => Some(sys_linux_pkey_free(arg1)),
        linux_nr::IO_PGETEVENTS => Some(sys_linux_io_pgetevents(
            arg1,
            arg2,
            arg3,
            UserPtr::new(arg4),
            UserPtr::new(arg5),
            UserPtr::new(arg6),
        )),
        linux_nr::RSEQ => Some(sys_linux_rseq(UserPtr::new(arg1), arg2, arg3, arg4)),
        linux_nr::PIDFD_SEND_SIGNAL => Some(sys_linux_pidfd_send_signal(
            Fd::from(arg1),
            arg2,
            UserPtr::new(arg3),
            arg4,
        )),
        linux_nr::IO_URING_SETUP => Some(sys_linux_io_uring_setup(arg1, UserPtr::new(arg2))),
        linux_nr::IO_URING_ENTER => Some(sys_linux_io_uring_enter(
            Fd::from(arg1),
            arg2,
            arg3,
            arg4,
            UserPtr::new(arg5),
        )),
        linux_nr::IO_URING_REGISTER => Some(sys_linux_io_uring_register(
            Fd::from(arg1),
            arg2,
            UserPtr::new(arg3),
            arg4,
        )),
        linux_nr::FSCONFIG => Some(sys_linux_fsconfig(
            Fd::from(arg1),
            arg2,
            UserPtr::new(arg3),
            UserPtr::new(arg4),
            arg5,
        )),
        linux_nr::PIDFD_OPEN => Some(sys_linux_pidfd_open(arg1, arg2)),
        linux_nr::CLONE3 => Some(sys_linux_clone3(frame, UserPtr::new(arg1), arg2)),
        linux_nr::PIDFD_GETFD => Some(sys_linux_pidfd_getfd(Fd::from(arg1), arg2, arg3)),
        linux_nr::PROCESS_MADVISE => Some(sys_linux_process_madvise(
            Fd::from(arg1),
            UserPtr::new(arg2),
            arg3,
            arg4,
            arg5,
        )),
        linux_nr::QUOTACTL_FD => Some(sys_linux_quotactl_fd(
            Fd::from(arg1),
            arg2,
            arg3,
            UserPtr::new(arg4),
        )),
        linux_nr::LANDLOCK_CREATE_RULESET => Some(sys_linux_landlock_create_ruleset(
            UserPtr::new(arg1),
            arg2,
            arg3,
        )),
        linux_nr::LANDLOCK_ADD_RULE => Some(sys_linux_landlock_add_rule(
            Fd::from(arg1),
            arg2,
            UserPtr::new(arg3),
            arg4,
        )),
        linux_nr::LANDLOCK_RESTRICT_SELF => {
            Some(sys_linux_landlock_restrict_self(Fd::from(arg1), arg2))
        }
        linux_nr::MEMFD_SECRET => Some(sys_linux_memfd_secret(arg1)),
        linux_nr::PROCESS_MRELEASE => Some(sys_linux_process_mrelease(Fd::from(arg1), arg2)),
        linux_nr::CACHESTAT => Some(sys_linux_cachestat(
            Fd::from(arg1),
            UserPtr::new(arg2),
            UserPtr::new(arg3),
            arg4,
        )),
        linux_nr::PTRACE => Some(sys_linux_ptrace(arg1, arg2, arg3, arg4)),
        linux_nr::SECCOMP => Some(sys_linux_seccomp(arg1, arg2, UserPtr::new(arg3))),
        _ => None,
    }
}
