use super::*;

pub(super) const PAGE_SIZE_BYTES: usize = 4096;
pub(super) const MIN_REBALANCE_INTERVAL_TICKS: u64 = 1;
pub(super) const MIN_REBALANCE_BATCH_SIZE: usize = 1;
pub(super) const MIN_REBALANCE_PREFER_LOCAL_SKIP_BUDGET: usize = 0;
pub(super) const MIN_LIBNET_FAST_PATH_PUMP_BUDGET: usize = 1;
pub(super) const DEFAULT_WATCHDOG_HARD_STALL_NS: u64 = GOVERNOR_WATCHDOG_HARD_STALL_NS;
pub(super) const DEFAULT_RT_FORCE_MIN_TICKS: usize = GOVERNOR_RT_FORCE_MIN_TICKS;
pub(super) const DEFAULT_RT_DEADLINE_BURST_THRESHOLD: usize = GOVERNOR_RT_DEADLINE_BURST_THRESHOLD;
pub(super) const DEFAULT_MODULE_LOADER_MAX_LOAD_SEGMENTS: usize = 128;
pub(super) const DEFAULT_MODULE_LOADER_MAX_TOTAL_IMAGE_BYTES: u64 = 1 << 30;
pub(super) const DEFAULT_LAUNCH_MAX_PROCESS_NAME_LEN: usize = 32;
pub(super) const DEFAULT_LAUNCH_MAX_BOOT_IMAGE_BYTES: usize = 1024 * 1024;
pub(super) const DEFAULT_LAUNCH_STAGE_TIMEOUT_EPOCHS: u64 = 256;
pub(super) const DEFAULT_VFS_MAX_MOUNTS: usize = VFS_MAX_MOUNTS;
pub(super) const DEFAULT_VFS_MAX_MOUNT_PATH: usize = VFS_MAX_MOUNT_PATH;
pub(super) const DEFAULT_VFS_HEALTH_MAX_FAILURE_RATE_PER_MILLE: u64 = 50;
pub(super) const DEFAULT_VFS_HEALTH_MAX_PATH_VALIDATION_FAILURES: u64 = 8;
pub(super) const DEFAULT_VFS_HEALTH_MAX_MOUNT_CAPACITY_PERCENT: usize = 90;
pub(super) const DEFAULT_IRQ_VECTOR_BASE: u8 = 32;
pub(super) const DEFAULT_POWER_RUNQUEUE_SATURATION_LIMIT: usize = GOVERNOR_POWER_RUNQUEUE_SATURATION_LIMIT;
pub(super) const DEFAULT_IRQSAFE_MUTEX_DEADLOCK_SPIN_LIMIT: usize = GOVERNOR_IRQSAFE_MUTEX_DEADLOCK_SPIN_LIMIT;
pub(super) const DEFAULT_LOAD_BALANCE_PERCENTILE_WINDOW: usize = GOVERNOR_LOAD_BALANCE_PERCENTILE_WINDOW;
pub(super) const DEFAULT_RUNTIME_POLICY_DRIFT_SAMPLE_INTERVAL_TICKS: u64 =
    GOVERNOR_RUNTIME_POLICY_DRIFT_SAMPLE_INTERVAL_TICKS;
pub(super) const DEFAULT_RUNTIME_POLICY_DRIFT_REAPPLY_COOLDOWN_TICKS: u64 =
    GOVERNOR_RUNTIME_POLICY_DRIFT_REAPPLY_COOLDOWN_TICKS;
pub(super) const DEFAULT_DISKFS_MAX_PATH_LEN: usize = 255;
pub(super) const DEFAULT_LIBNET_POLL_INTERVAL_LOW_LATENCY: u64 = 1;
pub(super) const DEFAULT_LIBNET_POLL_INTERVAL_BALANCED: u64 = 2;
pub(super) const DEFAULT_LIBNET_POLL_INTERVAL_POWERSAVE: u64 = 8;
pub(super) const DEFAULT_LIBNET_ADAPTIVE_QUEUE_DEPTH_DIVISOR: usize = 2;
pub(super) const DEFAULT_LIBNET_ADAPTIVE_HEALTH_LOW_THRESHOLD: u64 = 8;
pub(super) const DEFAULT_LIBNET_ADAPTIVE_POLL_HIGH_THRESHOLD: u64 = 4;
pub(super) const DEFAULT_NETWORK_RUNTIME_POLL_INTERVAL_MIN: u64 = 1;
pub(super) const DEFAULT_NETWORK_EPOLL_MAX_EVENTS: usize = 1024;
pub(super) const DEFAULT_NETWORK_EPOLL_MAX_FDS_PER_INSTANCE: usize = 4096;
pub(super) const DEFAULT_NETWORK_LOOPBACK_QUEUE_LIMIT: usize = NETWORK_LOOPBACK_QUEUE_LIMIT;
pub(super) const DEFAULT_NETWORK_UDP_QUEUE_LIMIT: usize = NETWORK_UDP_QUEUE_LIMIT;
pub(super) const DEFAULT_NETWORK_TCP_QUEUE_LIMIT: usize = NETWORK_TCP_QUEUE_LIMIT;
pub(super) const DEFAULT_NETWORK_FILTER_RULE_LIMIT: usize = NETWORK_FILTER_RULE_LIMIT;
pub(super) const DEFAULT_NETWORK_WIREGUARD_MAX_PEERS: usize = NETWORK_WIREGUARD_MAX_PEERS;
pub(super) const DEFAULT_NETWORK_HTTP_ASSET_LIMIT: usize = NETWORK_HTTP_ASSET_LIMIT;
pub(super) const DEFAULT_NETWORK_SLO_SAMPLE_INTERVAL: u64 = NETWORK_SLO_SAMPLE_INTERVAL;
pub(super) const DEFAULT_NETWORK_SLO_LOG_INTERVAL_MULTIPLIER: u64 = NETWORK_SLO_LOG_INTERVAL_MULTIPLIER;
pub(super) const DEFAULT_NETWORK_TLS_POLICY_PROFILE: &'static str = NETWORK_TLS_POLICY_PROFILE;
pub(super) const DEFAULT_LIBNET_POSIX_FD_START: u32 = NETWORK_POSIX_FD_START;
pub(super) const DEFAULT_LIBNET_POSIX_EPHEMERAL_START: u16 = NETWORK_POSIX_EPHEMERAL_START;
pub(super) const DEFAULT_LIBNET_POSIX_BLOCKING_RECV_RETRIES: usize = NETWORK_BLOCKING_RECV_RETRIES;
pub(super) const DEFAULT_DRIVER_NETWORK_IRQ_SERVICE_BUDGET: usize = DRIVER_NETWORK_IRQ_SERVICE_BUDGET;
pub(super) const DEFAULT_DRIVER_NETWORK_LOOP_SERVICE_BUDGET: usize = DRIVER_NETWORK_LOOP_SERVICE_BUDGET;
pub(super) const DEFAULT_DRIVER_NETWORK_RING_LIMIT: usize = DRIVER_NETWORK_RING_LIMIT;
pub(super) const DEFAULT_DRIVER_NETWORK_QUARANTINE_REBIND_FAILURES: u64 =
    DRIVER_NETWORK_QUARANTINE_REBIND_FAILURES;
pub(super) const DEFAULT_DRIVER_NETWORK_QUARANTINE_COOLDOWN_SAMPLES: u64 =
    DRIVER_NETWORK_QUARANTINE_COOLDOWN_SAMPLES;
pub(super) const DEFAULT_DRIVER_NETWORK_SLO_MAX_DROP_RATE_PER_MILLE: u64 =
    DRIVER_NETWORK_SLO_MAX_DROP_RATE_PER_MILLE;
pub(super) const DEFAULT_DRIVER_NETWORK_SLO_MAX_TX_RING_UTILIZATION_PERCENT: u64 =
    DRIVER_NETWORK_SLO_MAX_TX_RING_UTILIZATION_PERCENT;
pub(super) const DEFAULT_DRIVER_NETWORK_SLO_MAX_RX_RING_UTILIZATION_PERCENT: u64 =
    DRIVER_NETWORK_SLO_MAX_RX_RING_UTILIZATION_PERCENT;
pub(super) const DEFAULT_DRIVER_NETWORK_SLO_MAX_IO_ERRORS: u64 = DRIVER_NETWORK_SLO_MAX_IO_ERRORS;
pub(super) const DEFAULT_DRIVER_NETWORK_LOW_LATENCY_IRQ_BUDGET_DIVISOR: usize =
    DRIVER_NETWORK_LOW_LATENCY_IRQ_BUDGET_DIVISOR;
pub(super) const DEFAULT_DRIVER_NETWORK_LOW_LATENCY_LOOP_BUDGET_DIVISOR: usize =
    DRIVER_NETWORK_LOW_LATENCY_LOOP_BUDGET_DIVISOR;
pub(super) const DEFAULT_DRIVER_NETWORK_LOW_LATENCY_RING_LIMIT_DIVISOR: usize =
    DRIVER_NETWORK_LOW_LATENCY_RING_LIMIT_DIVISOR;
pub(super) const DEFAULT_DRIVER_NETWORK_THROUGHPUT_IRQ_BUDGET_MULTIPLIER: usize =
    DRIVER_NETWORK_THROUGHPUT_IRQ_BUDGET_MULTIPLIER;
pub(super) const DEFAULT_DRIVER_NETWORK_THROUGHPUT_LOOP_BUDGET_MULTIPLIER: usize =
    DRIVER_NETWORK_THROUGHPUT_LOOP_BUDGET_MULTIPLIER;
pub(super) const DEFAULT_DRIVER_NETWORK_THROUGHPUT_RING_LIMIT_MULTIPLIER: usize =
    DRIVER_NETWORK_THROUGHPUT_RING_LIMIT_MULTIPLIER;
pub(super) const DEFAULT_AHCI_IO_TIMEOUT_SPINS: usize = DRIVER_AHCI_IO_TIMEOUT_SPINS;
pub(super) const DEFAULT_NVME_DISABLE_READY_TIMEOUT_SPINS: usize = DRIVER_NVME_DISABLE_READY_TIMEOUT_SPINS;
pub(super) const DEFAULT_NVME_POLL_TIMEOUT_SPINS: usize = DRIVER_NVME_POLL_TIMEOUT_SPINS;
pub(super) const DEFAULT_NVME_IO_TIMEOUT_SPINS: usize = DRIVER_NVME_IO_TIMEOUT_SPINS;
pub(super) const DEFAULT_E1000_RESET_TIMEOUT_SPINS: usize = DRIVER_E1000_RESET_TIMEOUT_SPINS;
pub(super) const DEFAULT_E1000_BUFFER_SIZE_BYTES: usize = DRIVER_E1000_BUFFER_SIZE_BYTES;
pub(super) const DEFAULT_E1000_RX_DESC_COUNT: usize = DRIVER_E1000_RX_DESC_COUNT;
pub(super) const DEFAULT_E1000_TX_DESC_COUNT: usize = DRIVER_E1000_TX_DESC_COUNT;
pub(super) const DEFAULT_SYSCALL_MAX_PATH_LEN: usize = LINUX_MAX_PATH_LEN;
pub(super) const DEFAULT_SCHED_LOTTERY_INITIAL_SEED: u64 = SCHED_LOTTERY_INITIAL_SEED;
pub(super) const DEFAULT_SCHED_LOTTERY_TICKETS_PER_PRIORITY_LEVEL: u64 = SCHED_LOTTERY_TICKETS_PER_PRIORITY;
pub(super) const DEFAULT_SCHED_LOTTERY_MIN_TICKETS_PER_TASK: u64 = SCHED_LOTTERY_MIN_TICKETS;
pub(super) const DEFAULT_SCHED_LOTTERY_LCG_MULTIPLIER: u64 = SCHED_LOTTERY_LCG_MULTIPLIER;
pub(super) const DEFAULT_SCHED_LOTTERY_LCG_INCREMENT: u64 = SCHED_LOTTERY_LCG_INCREMENT;
pub(super) const DEFAULT_SCHED_CFS_MIN_GRANULARITY_NS: u64 = SCHED_CFS_MIN_GRANULARITY_NS;
pub(super) const DEFAULT_SCHED_CFS_LATENCY_TARGET_NS: u64 = SCHED_CFS_LATENCY_TARGET_NS;
pub(super) const DEFAULT_SCHED_MLFQ_BASE_SLICE_NS: u64 = SCHED_MLFQ_BASE_SLICE_NS;
pub(super) const DEFAULT_SCHED_MLFQ_BOOST_INTERVAL_TICKS: u64 = SCHED_MLFQ_BOOST_INTERVAL_TICKS;
pub(super) const DEFAULT_SCHED_MLFQ_DEMOTE_ON_SLICE_EXHAUSTION: bool = SCHED_MLFQ_DEMOTE_ON_SLICE_EXHAUSTION;
pub(super) const DEFAULT_SCHED_EDF_ENFORCE_DEADLINE: bool = SCHED_EDF_ENFORCE_DEADLINE;
pub(super) const DEFAULT_SCHED_EDF_DEFAULT_RELATIVE_DEADLINE_NS: u64 = SCHED_EDF_DEFAULT_RELATIVE_DEADLINE_NS;
pub(super) const DEFAULT_SCHED_RT_ENABLE_GROUP_RESERVATION: bool = SCHED_RT_ENABLE_GROUP_RESERVATION;
pub(super) const DEFAULT_SCHED_RT_PERIOD_NS: u64 = SCHED_RT_PERIOD_NS;
pub(super) const DEFAULT_SCHED_RT_TOTAL_UTILIZATION_CAP_PERCENT: u8 = SCHED_RT_TOTAL_UTILIZATION_CAP_PERCENT;
pub(super) const DEFAULT_SCHED_RT_MAX_GROUPS: usize = SCHED_RT_MAX_GROUPS;
pub(super) const MAX_IRQ_VECTOR_BASE: u8 = 240;
pub(super) const MAX_WATCHDOG_HARD_STALL_NS: u64 = 120_000_000_000;
pub(super) const MAX_RT_FORCE_MIN_TICKS: usize = 1_000_000;
pub(super) const MAX_RT_DEADLINE_BURST_THRESHOLD: usize = 1_000_000;
pub(super) const MAX_MODULE_LOADER_MAX_LOAD_SEGMENTS: usize = 4096;
pub(super) const MAX_MODULE_LOADER_MAX_TOTAL_IMAGE_BYTES: u64 = 16 * 1024 * 1024 * 1024;
pub(super) const MAX_LAUNCH_MAX_PROCESS_NAME_LEN: usize = 32;
pub(super) const MAX_LAUNCH_MAX_BOOT_IMAGE_BYTES: usize = 64 * 1024 * 1024;
pub(super) const MAX_LAUNCH_STAGE_TIMEOUT_EPOCHS: u64 = 1_000_000;
pub(super) const MAX_VFS_MAX_MOUNTS: usize = 8192;
pub(super) const MAX_VFS_MAX_MOUNT_PATH: usize = 4096;
pub(super) const MAX_VFS_HEALTH_MAX_FAILURE_RATE_PER_MILLE: u64 = 1_000;
pub(super) const MAX_VFS_HEALTH_MAX_PATH_VALIDATION_FAILURES: u64 = 65_536;
pub(super) const MAX_VFS_HEALTH_MAX_MOUNT_CAPACITY_PERCENT: usize = 100;
pub(super) const MAX_REBALANCE_PREFER_LOCAL_SKIP_BUDGET: usize = 1_000_000;
pub(super) const DEFAULT_LINUX_RELEASE: &'static str = LINUX_RELEASE_STR;
pub(super) const DEFAULT_LINUX_VERSION: &'static str = LINUX_VERSION_STR;
pub(super) const MAX_POWER_RUNQUEUE_SATURATION_LIMIT: usize = 1_000_000;
pub(super) const MAX_IRQSAFE_MUTEX_DEADLOCK_SPIN_LIMIT: usize = 1_000_000_000;
pub(super) const MAX_LOAD_BALANCE_PERCENTILE_WINDOW: usize = 65_536;
pub(super) const MAX_RUNTIME_POLICY_DRIFT_SAMPLE_INTERVAL_TICKS: u64 = 1_000_000_000;
pub(super) const MAX_RUNTIME_POLICY_DRIFT_REAPPLY_COOLDOWN_TICKS: u64 = 1_000_000_000;
pub(super) const MAX_DISKFS_MAX_PATH_LEN: usize = 4096;
pub(super) const MAX_DEVFS_DEFAULT_MODE: u16 = 0o777;
pub(super) const MAX_LIBNET_POLL_INTERVAL: u64 = 10_000;
pub(super) const MAX_LIBNET_ADAPTIVE_QUEUE_DEPTH_DIVISOR: usize = 64;
pub(super) const MAX_LIBNET_ADAPTIVE_HEALTH_LOW_THRESHOLD: u64 = 100;
pub(super) const MAX_LIBNET_ADAPTIVE_POLL_HIGH_THRESHOLD: u64 = 10_000;
pub(super) const MAX_NETWORK_RUNTIME_POLL_INTERVAL_MIN: u64 = 10_000;
pub(super) const MAX_NETWORK_EPOLL_MAX_EVENTS: usize = 65_536;
pub(super) const MAX_NETWORK_EPOLL_MAX_FDS_PER_INSTANCE: usize = 65_536;
pub(super) const MAX_NETWORK_LOOPBACK_QUEUE_LIMIT: usize = 65_536;
pub(super) const MAX_NETWORK_UDP_QUEUE_LIMIT: usize = 65_536;
pub(super) const MAX_NETWORK_TCP_QUEUE_LIMIT: usize = 65_536;
pub(super) const MAX_NETWORK_FILTER_RULE_LIMIT: usize = 16_384;
pub(super) const MAX_NETWORK_WIREGUARD_MAX_PEERS: usize = 65_536;
pub(super) const MAX_NETWORK_HTTP_ASSET_LIMIT: usize = 65_536;
pub(super) const MAX_NETWORK_SLO_SAMPLE_INTERVAL: u64 = 1_000_000_000;
pub(super) const MAX_NETWORK_SLO_LOG_INTERVAL_MULTIPLIER: u64 = 1_000_000_000;
pub(super) const MAX_LIBNET_POSIX_FD_START: u32 = i32::MAX as u32;
pub(super) const MAX_LIBNET_POSIX_EPHEMERAL_START: u16 = 65_534;
pub(super) const MAX_LIBNET_POSIX_BLOCKING_RECV_RETRIES: usize = 1_000_000;
pub(super) const MAX_DRIVER_NETWORK_SERVICE_BUDGET: usize = 65_536;
pub(super) const MAX_DRIVER_NETWORK_RING_LIMIT: usize = 65_536;
pub(super) const MAX_DRIVER_NETWORK_QUARANTINE_REBIND_FAILURES: u64 = 1_000_000;
pub(super) const MAX_DRIVER_NETWORK_QUARANTINE_COOLDOWN_SAMPLES: u64 = 1_000_000;
pub(super) const MAX_DRIVER_NETWORK_PROFILE_TUNING_FACTOR: usize = 1024;
pub(super) const MAX_DRIVER_WAIT_TIMEOUT_SPINS: usize = 100_000_000;
pub(super) const MAX_E1000_BUFFER_SIZE_BYTES: usize = 16_384;
pub(super) const MAX_E1000_DESC_COUNT: usize = 4096;
pub(super) const MAX_SYSCALL_MAX_PATH_LEN: usize = 65_536;
pub(super) const MAX_SCHED_LOTTERY_TICKETS_PER_PRIORITY_LEVEL: u64 = 1_000_000;
pub(super) const MAX_SCHED_LOTTERY_MIN_TICKETS_PER_TASK: u64 = 1_000_000;
pub(super) const MAX_SCHED_LOTTERY_LCG_PARAM: u64 = u64::MAX;
pub(super) const MAX_SCHED_CFS_MIN_GRANULARITY_NS: u64 = 10_000_000_000;
pub(super) const MAX_SCHED_CFS_LATENCY_TARGET_NS: u64 = 60_000_000_000;
pub(super) const MAX_SCHED_MLFQ_BASE_SLICE_NS: u64 = 60_000_000_000;
pub(super) const MAX_SCHED_MLFQ_BOOST_INTERVAL_TICKS: u64 = 1_000_000_000;
pub(super) const MAX_SCHED_EDF_DEFAULT_RELATIVE_DEADLINE_NS: u64 = 60_000_000_000;
pub(super) const MAX_SCHED_RT_PERIOD_NS: u64 = 60_000_000_000;
pub(super) const MAX_SCHED_RT_TOTAL_UTILIZATION_CAP_PERCENT: u8 = 100;
pub(super) const MAX_SCHED_RT_MAX_GROUPS: usize = 65_536;
pub(super) const DEFAULT_TELEMETRY_HISTORY_LEN: usize = TELEMETRY_HISTORY_LEN;
pub(super) const MAX_TELEMETRY_HISTORY_LEN: usize = 1_000_000;
pub(super) const DEFAULT_TELEMETRY_LOG_LEVEL_NUM: u8 = LOG_LEVEL_NUM;
pub(super) const MIN_TELEMETRY_LOG_LEVEL_NUM: u8 = 1;
pub(super) const MAX_TELEMETRY_LOG_LEVEL_NUM: u8 = 5;

#[inline(always)]
pub(super) fn normalize_e1000_desc_count(raw: usize, default: usize) -> usize {
    let clamped = if raw == 0 {
        default
    } else {
        raw.clamp(8, MAX_E1000_DESC_COUNT)
    };
    ((clamped + 7) / 8) * 8
}
