[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=0x1000"]

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=0x1000"]

[alias]
xtask = ["run", "--package", "xtask", "--target-dir", "target/xtask", "--"]
kbuild = "build --package hypercore --target x86_64-unknown-none"
akbuild = "build --package hypercore --target aarch64-unknown-none"
