use core::sync::atomic::AtomicU64;

pub(super) static SMOLTCP_BRIDGE_INITS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_POLLS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_RX_FRAMES: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_TX_FRAMES: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_TICKS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_FORCE_POLLS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_REINITIALIZE_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_INIT_ERRORS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_POLL_ERRORS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_POLL_SKIPS: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_RUNTIME_POLL_ENABLED: AtomicU64 = AtomicU64::new(1);
pub(super) static SMOLTCP_RUNTIME_CONTROL_UPDATES: AtomicU64 = AtomicU64::new(0);
pub(super) static SMOLTCP_POLL_INTERVAL_TICKS: AtomicU64 = AtomicU64::new(1);
pub(super) static LOOPBACK_SEND_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static LOOPBACK_SEND_DROPS: AtomicU64 = AtomicU64::new(0);
pub(super) static LOOPBACK_RECEIVE_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static LOOPBACK_RECEIVE_HITS: AtomicU64 = AtomicU64::new(0);
pub(super) static LOOPBACK_QUEUE_HIGH_WATER: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_BIND_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_DROPS: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_HITS: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_QUEUE_HIGH_WATER: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_LISTEN_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_CONNECT_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_ACCEPT_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_ACCEPT_HITS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_DROPS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_HITS: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_QUEUE_HIGH_WATER: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_LAT_BUCKET_0: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_LAT_BUCKET_1: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_LAT_BUCKET_2_3: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_LAT_BUCKET_4_7: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_SEND_LAT_BUCKET_GE8: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_LAT_BUCKET_0: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_LAT_BUCKET_1: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_LAT_BUCKET_2_3: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_LAT_BUCKET_4_7: AtomicU64 = AtomicU64::new(0);
pub(super) static UDP_RECV_LAT_BUCKET_GE8: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_LAT_BUCKET_0: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_LAT_BUCKET_1: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_LAT_BUCKET_2_3: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_LAT_BUCKET_4_7: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_SEND_LAT_BUCKET_GE8: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_LAT_BUCKET_0: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_LAT_BUCKET_1: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_LAT_BUCKET_2_3: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_LAT_BUCKET_4_7: AtomicU64 = AtomicU64::new(0);
pub(super) static TCP_RECV_LAT_BUCKET_GE8: AtomicU64 = AtomicU64::new(0);
pub(super) static DNS_REGISTER_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static DNS_RESOLVE_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static DNS_RESOLVE_HITS: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_REGISTER_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_REMOVE_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_CLEAR_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_EVAL_CALLS: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_EVAL_ALLOW: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_EVAL_DROP: AtomicU64 = AtomicU64::new(0);
pub(super) static FILTER_NEXT_ID: AtomicU64 = AtomicU64::new(1);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_ADD_PEER_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_REMOVE_PEER_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_ENCAP_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_DECAP_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_DROP_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_BYTES_ENCAP: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_BYTES_DECAP: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_ACTIVE_PEERS_HIGH_WATER: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_wireguard")]
pub(super) static WG_NEXT_PEER_ID: AtomicU64 = AtomicU64::new(1);
#[cfg(feature = "network_http")]
pub(super) static HTTP_REGISTER_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_REMOVE_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_REQUEST_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_RESP_200: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_RESP_304: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_RESP_404: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_SENDFILE_CALLS: AtomicU64 = AtomicU64::new(0);
#[cfg(feature = "network_http")]
pub(super) static HTTP_BYTES_SERVED: AtomicU64 = AtomicU64::new(0);
pub(super) static BACKPRESSURE_DROP_ACTIONS: AtomicU64 = AtomicU64::new(0);
pub(super) static BACKPRESSURE_DEFER_ACTIONS: AtomicU64 = AtomicU64::new(0);
pub(super) static BACKPRESSURE_FORCE_POLL_ACTIONS: AtomicU64 = AtomicU64::new(0);
pub(super) static LOOPBACK_BACKPRESSURE_POLICY: AtomicU64 = AtomicU64::new(BACKPRESSURE_POLICY_DROP_RAW);
#[cfg(feature = "network_transport")]
pub(super) static UDP_BACKPRESSURE_POLICY: AtomicU64 = AtomicU64::new(BACKPRESSURE_POLICY_DROP_RAW);
#[cfg(feature = "network_transport")]
pub(super) static TCP_BACKPRESSURE_POLICY: AtomicU64 = AtomicU64::new(BACKPRESSURE_POLICY_DROP_RAW);
pub(super) static ALERT_MIN_HEALTH_SCORE: AtomicU64 = AtomicU64::new(ALERT_MIN_HEALTH_SCORE_DEFAULT);
pub(super) static ALERT_MAX_DROPS: AtomicU64 = AtomicU64::new(ALERT_LIMIT_OPEN_MAX);
pub(super) static ALERT_MAX_QUEUE_HIGH_WATER: AtomicU64 = AtomicU64::new(ALERT_LIMIT_OPEN_MAX);

pub(super) const BACKPRESSURE_POLICY_DROP_RAW: u64 = 0;
pub(super) const BACKPRESSURE_POLICY_DEFER_RAW: u64 = 1;
pub(super) const BACKPRESSURE_POLICY_FORCE_POLL_RAW: u64 = 2;
pub(super) const ALERT_MIN_HEALTH_SCORE_DEFAULT: u64 = 0;
pub(super) const ALERT_LIMIT_OPEN_MAX: u64 = u64::MAX;
pub(super) const PERCENTILE_SCALE: u64 = 100;
pub(super) const PERCENTILE_ROUNDING_BIAS: u64 = PERCENTILE_SCALE - 1;
pub(super) const PERCENTILE_P50: u64 = 50;
pub(super) const PERCENTILE_P95: u64 = 95;
pub(super) const PERCENTILE_P99: u64 = 99;
pub(super) const LATENCY_TICKS_BUCKET_0: u64 = 0;
pub(super) const LATENCY_TICKS_BUCKET_1: u64 = 1;
pub(super) const LATENCY_TICKS_BUCKET_2_3_MAX: u64 = 3;
pub(super) const LATENCY_TICKS_BUCKET_4_7_MAX: u64 = 7;
pub(super) const LATENCY_TICKS_BUCKET_GE8: u64 = 8;