pub(crate) struct VirtualizationLogSnapshot {
    pub backend: &'static str,
    pub lifecycle_summary: &'static str,
    pub lifecycle_progress_per_mille: u16,
    pub detect_state: &'static str,
    pub prepare_state: &'static str,
    pub capability_state: &'static str,
    pub feature_state: &'static str,
    pub launch_state: &'static str,
    pub resume_state: &'static str,
    pub trap_state: &'static str,
    pub runtime_step: &'static str,
    pub execution_profile: &'static str,
    pub execution_profile_scope: &'static str,
    pub governor_profile: &'static str,
    pub governor_profile_scope: &'static str,
    pub dispatch_class: &'static str,
    pub preemption_policy: &'static str,
    pub scheduler_lane: &'static str,
    pub dispatch_window: &'static str,
    pub runtime_strategy: &'static str,
    pub runtime_budget_class: &'static str,
    pub aux_step: &'static str,
    pub operation_class: &'static str,
    pub blocked_by: Option<&'static str>,
    pub policy_limited_by: Option<&'static str>,
    pub policy_scope: &'static str,
    pub entry_scope: &'static str,
    pub resume_scope: &'static str,
    pub trap_scope: &'static str,
    pub nested_scope: &'static str,
    pub time_scope: &'static str,
    pub passthrough_scope: &'static str,
    pub entry_mode: &'static str,
    pub resume_mode: &'static str,
    pub trap_mode: &'static str,
    pub nested_mode: &'static str,
    pub time_mode: &'static str,
    pub passthrough_mode: &'static str,
    pub selected_mode: &'static str,
    pub governor_class: &'static str,
    pub latency_bias: &'static str,
    pub energy_bias: &'static str,
}

pub(crate) fn current_virtualization_log_snapshot() -> VirtualizationLogSnapshot {
    let virt = aethercore::hal::platform::status();
    VirtualizationLogSnapshot {
        backend: virt.virt_backend,
        lifecycle_summary: virt.virt_lifecycle_summary,
        lifecycle_progress_per_mille: virt.virt_lifecycle_progress_per_mille,
        detect_state: virt.virt_detect_state,
        prepare_state: virt.virt_prepare_state,
        capability_state: virt.virt_capability_state,
        feature_state: virt.virt_feature_state,
        launch_state: virt.virt_launch_state,
        resume_state: virt.virt_resume_state,
        trap_state: virt.virt_trap_state,
        runtime_step: virt.virt_runtime_step,
        execution_profile: virt.virt_runtime_execution_profile,
        execution_profile_scope: virt.virt_runtime_execution_profile_scope,
        governor_profile: virt.virt_runtime_governor_profile,
        governor_profile_scope: virt.virt_runtime_governor_profile_scope,
        dispatch_class: virt.virt_runtime_dispatch_class,
        preemption_policy: virt.virt_runtime_preemption_policy,
        scheduler_lane: virt.virt_runtime_scheduler_lane,
        dispatch_window: virt.virt_runtime_dispatch_window,
        runtime_strategy: virt.virt_runtime_strategy,
        runtime_budget_class: virt.virt_runtime_budget_class,
        aux_step: virt.virt_runtime_aux_step,
        operation_class: virt.virt_runtime_operation_class,
        blocked_by: virt.virt_runtime_blocked_by,
        policy_limited_by: virt.virt_runtime_policy_limited_by,
        policy_scope: virt.virt_policy_scope,
        entry_scope: virt.virt_entry_policy_scope,
        resume_scope: virt.virt_resume_policy_scope,
        trap_scope: virt.virt_trap_dispatch_policy_scope,
        nested_scope: virt.virt_nested_policy_scope,
        time_scope: virt.virt_time_virtualization_policy_scope,
        passthrough_scope: virt.virt_device_passthrough_policy_scope,
        entry_mode: virt.virt_entry_mode,
        resume_mode: virt.virt_resume_mode,
        trap_mode: virt.virt_trap_mode,
        nested_mode: virt.virt_nested_mode,
        time_mode: virt.virt_time_mode,
        passthrough_mode: virt.virt_device_passthrough_mode,
        selected_mode: virt.virt_runtime_selected_mode,
        governor_class: virt.virt_runtime_governor_class,
        latency_bias: virt.virt_runtime_latency_bias,
        energy_bias: virt.virt_runtime_energy_bias,
    }
}
