//! Generates src/generated_consts.rs from the parsed Config.

use super::config_types::Config;
use super::feature_graph::{
    feature_enabled, feature_primary_group, load_feature_graph_from_manifest,
};

/// Produces the full content of generated_consts.rs.
pub fn emit_all_consts(config: &Config) -> String {
    let mut c = String::with_capacity(16 * 1024);

    c.push_str("//! AUTO-GENERATED CONFIGURATION - DO NOT EDIT\n");
    c.push_str(
        "//! Generated by build.rs from Cargo.toml [package.metadata.aethercore.config]\n\n",
    );

    // ── Meta ──────────────────────────────────────────────────────────────
    c.push_str(&format!(
        "pub const META_PROFILE: &str = \"{}\";\n",
        config.meta.profile
    ));
    c.push_str(&format!(
        "pub const META_VERSION: &str = \"{}\";\n",
        config.meta.version
    ));

    // ── Kernel ────────────────────────────────────────────────────────────
    c.push_str(&format!(
        "pub const TIME_SLICE_NS: u64 = {};\n",
        config.kernel.time_slice_ns
    ));
    c.push_str(&format!(
        "pub const STACK_SIZE_PAGES: usize = {};\n",
        config.kernel.stack_size_pages
    ));
    c.push_str(&format!(
        "pub const KERNEL_MAX_CPUS: usize = {};\n",
        config.kernel.max_cpus
    ));
    c.push_str(&format!(
        "pub const INTERRUPT_STACK_SIZE_PAGES: usize = {};\n",
        config.kernel.interrupt_stack_size_pages
    ));
    c.push_str(&format!(
        "pub const TARGET_ARCH: &str = \"{}\";\n",
        config.kernel.arch
    ));

    // ── Boot ──────────────────────────────────────────────────────────────
    c.push_str(&format!(
        "pub const BOOT_CMDLINE_PARSE: bool = {};\n",
        config.boot.cmdline_parse
    ));
    c.push_str(&format!(
        "pub const BOOT_SPLASH: bool = {};\n",
        config.boot.splash_screen
    ));
    c.push_str(&format!(
        "pub const BOOT_QUIET: bool = {};\n",
        config.boot.quiet_boot
    ));

    // ── Library ───────────────────────────────────────────────────────────
    emit_library(&mut c, config);

    // ── Core toggles ──────────────────────────────────────────────────────
    emit_core(&mut c, config);

    // ── Memory ────────────────────────────────────────────────────────────
    emit_memory(&mut c, config);

    // ── Scheduler ─────────────────────────────────────────────────────────
    emit_scheduler(&mut c, config);

    // ── Dispatcher ────────────────────────────────────────────────────────
    c.push_str(&format!(
        "pub const DISPATCHER_BUFFER_SIZE: usize = {};\n",
        config.dispatcher.buffer_size
    ));
    c.push_str(&format!(
        "pub const DISPATCHER_VECTOR_ALIGN: usize = {};\n",
        config.dispatcher.vector_table_align
    ));

    // ── IPC ───────────────────────────────────────────────────────────────
    emit_ipc(&mut c, config);

    // ── Security ──────────────────────────────────────────────────────────
    emit_security(&mut c, config);

    // ── Telemetry ─────────────────────────────────────────────────────────
    emit_telemetry(&mut c, config);

    // ── Linux Compat ──────────────────────────────────────────────────────
    emit_linux_compat(&mut c, config);

    // ── VFS ───────────────────────────────────────────────────────────────
    emit_vfs(&mut c, config);

    // ── Network ───────────────────────────────────────────────────────────
    emit_network(&mut c, config);

    // ── Drivers ───────────────────────────────────────────────────────────
    emit_drivers(&mut c, config);

    // ── Governor ──────────────────────────────────────────────────────────
    emit_governor(&mut c, config);

    // ── Linux OS Info ─────────────────────────────────────────────────────
    c.push_str(&format!(
        "pub const LINUX_RELEASE_STR: &str = \"{}\";\n",
        config.linux_os.release
    ));
    c.push_str(&format!(
        "pub const LINUX_VERSION_STR: &str = \"{}\";\n",
        config.linux_os.version
    ));

    // ── AArch64 ───────────────────────────────────────────────────────────
    emit_aarch64(&mut c, config);

    // ── Lottery Scheduler ─────────────────────────────────────────────────
    emit_lottery(&mut c, config);

    // ── Log level numeric ─────────────────────────────────────────────────
    let log_level_num = match config.telemetry.log_level.as_str() {
        "Error" => 1,
        "Warn" => 2,
        "Info" => 3,
        "Debug" => 4,
        "Trace" => 5,
        _ => 3,
    };
    c.push_str(&format!(
        "pub const LOG_LEVEL_NUM: u8 = {};\n",
        log_level_num
    ));

    // ── Feature catalog ───────────────────────────────────────────────────
    emit_feature_catalog(&mut c);

    c
}

// ─── Section emitters ─────────────────────────────────────────────────────────

fn emit_library(c: &mut String, config: &Config) {
    let lib = &config.library;
    c.push_str(&format!(
        "pub const LIBRARY_BOUNDARY_MODE: &str = \"{}\";\n",
        lib.boundary_mode
    ));
    c.push_str(&format!(
        "pub const LIBRARY_ENFORCE_CORE_MINIMAL: bool = {};\n",
        lib.enforce_core_minimal
    ));
    c.push_str(&format!(
        "pub const LIBRARY_STRICT_OPTIONAL_FEATURES: bool = {};\n",
        lib.strict_optional_features
    ));
    c.push_str(&format!(
        "pub const LIBRARY_EXPOSE_VFS_API: bool = {};\n",
        lib.expose_vfs_api
    ));
    c.push_str(&format!(
        "pub const LIBRARY_EXPOSE_NETWORK_API: bool = {};\n",
        lib.expose_network_api
    ));
    c.push_str(&format!(
        "pub const LIBRARY_EXPOSE_IPC_API: bool = {};\n",
        lib.expose_ipc_api
    ));
    c.push_str(&format!(
        "pub const LIBNET_L2_ENABLED: bool = {};\n",
        lib.libnet_l2_enabled
    ));
    c.push_str(&format!(
        "pub const LIBNET_L34_ENABLED: bool = {};\n",
        lib.libnet_l34_enabled
    ));
    c.push_str(&format!(
        "pub const LIBNET_L6_ENABLED: bool = {};\n",
        lib.libnet_l6_enabled
    ));
    c.push_str(&format!(
        "pub const LIBNET_L7_ENABLED: bool = {};\n",
        lib.libnet_l7_enabled
    ));
    c.push_str(&format!(
        "pub const LIBNET_FAST_PATH_DEFAULT_STRATEGY: &str = \"{}\";\n",
        lib.libnet_fast_path_default_strategy
    ));
    c.push_str(&format!(
        "pub const LIBNET_FAST_PATH_RUN_PUMP: bool = {};\n",
        lib.libnet_fast_path_run_pump
    ));
    c.push_str(&format!(
        "pub const LIBNET_FAST_PATH_COLLECT_TRANSPORT_SNAPSHOT: bool = {};\n",
        lib.libnet_fast_path_collect_transport_snapshot
    ));
    c.push_str(&format!(
        "pub const LIBNET_FAST_PATH_PUMP_BUDGET: usize = {};\n",
        lib.libnet_fast_path_pump_budget
    ));
    c.push_str(&format!(
        "pub const LIBRARY_MAX_SERVICES: usize = {};\n",
        lib.max_services
    ));
    c.push_str(&format!(
        "pub const LIBRARY_VERBOSE_BOOT_INVENTORY: bool = {};\n",
        lib.verbose_boot_inventory
    ));
}

fn emit_core(c: &mut String, config: &Config) {
    let co = &config.core;
    c.push_str(&format!(
        "pub const CORE_ENABLE_SMP: bool = {};\n",
        co.enable_smp
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_WORK_STEALING: bool = {};\n",
        co.enable_work_stealing
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_PCI_ENUMERATION: bool = {};\n",
        co.enable_pci_enumeration
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_ACPI_DISCOVERY: bool = {};\n",
        co.enable_acpi_discovery
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_IOMMU: bool = {};\n",
        co.enable_iommu
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_VIRTUALIZATION: bool = {};\n",
        co.enable_virtualization
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_DRIVER_INIT: bool = {};\n",
        co.enable_driver_init
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_TLS_SYSCALLS: bool = {};\n",
        co.enable_tls_syscalls
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_KERNEL_DUMP: bool = {};\n",
        co.enable_kernel_dump
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_EXTENDED_IRQ_VECTORS: bool = {};\n",
        co.enable_extended_irq_vectors
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_IRQ_TRACE: bool = {};\n",
        co.enable_irq_trace
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_SCHEDULER_TRACE: bool = {};\n",
        co.enable_scheduler_trace
    ));
    c.push_str(&format!(
        "pub const CORE_IDLE_STRATEGY: &str = \"{}\";\n",
        co.idle_strategy
    ));
    c.push_str(&format!(
        "pub const CORE_PANIC_ACTION: &str = \"{}\";\n",
        co.panic_action
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_PERIODIC_REBALANCE: bool = {};\n",
        co.enable_periodic_rebalance
    ));
    c.push_str(&format!(
        "pub const CORE_REBALANCE_INTERVAL_TICKS: u64 = {};\n",
        co.rebalance_interval_ticks
    ));
    c.push_str(&format!(
        "pub const CORE_REBALANCE_IMBALANCE_THRESHOLD: usize = {};\n",
        co.rebalance_imbalance_threshold
    ));
    c.push_str(&format!(
        "pub const CORE_REBALANCE_BATCH_SIZE: usize = {};\n",
        co.rebalance_batch_size
    ));
    c.push_str(&format!(
        "pub const CORE_REBALANCE_PREFER_LOCAL_SKIP_BUDGET: usize = {};\n",
        co.rebalance_prefer_local_skip_budget
    ));
    c.push_str(&format!(
        "pub const CORE_AFFINITY_POLICY: &str = \"{}\";\n",
        co.affinity_policy
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_AFFINITY_ENFORCEMENT: bool = {};\n",
        co.enable_affinity_enforcement
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_INTERRUPT_STORM_PROTECTION: bool = {};\n",
        co.enable_interrupt_storm_protection
    ));
    c.push_str(&format!(
        "pub const CORE_IRQ_STORM_THRESHOLD: u32 = {};\n",
        co.irq_storm_threshold
    ));
    c.push_str(&format!(
        "pub const CORE_IRQ_STORM_WINDOW_TICKS: u64 = {};\n",
        co.irq_storm_window_ticks
    ));
    c.push_str(&format!(
        "pub const CORE_ENABLE_SOFT_WATCHDOG: bool = {};\n",
        co.enable_soft_watchdog
    ));
    c.push_str(&format!(
        "pub const CORE_SOFT_WATCHDOG_STALL_TICKS: u64 = {};\n",
        co.soft_watchdog_stall_ticks
    ));
    c.push_str(&format!(
        "pub const CORE_SOFT_WATCHDOG_ACTION: &str = \"{}\";\n",
        co.soft_watchdog_action
    ));
    c.push_str(&format!(
        "pub const CORE_CRASH_LOG_CAPACITY: usize = {};\n",
        co.crash_log_capacity.max(1)
    ));
}

fn emit_memory(c: &mut String, config: &Config) {
    let m = &config.memory;
    c.push_str(&format!(
        "pub const MEM_HEAP_SIZE_MB: usize = {};\n",
        m.heap_size_mb
    ));
    c.push_str(&format!(
        "pub const MEM_GUARDIAN_PAGES: bool = {};\n",
        m.guardian_pages
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_REFILL_BYTES: usize = {};\n",
        m.slab_refill_bytes
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_CACHE_LIMIT: usize = {};\n",
        m.slab_cache_limit
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_RELEASE_BATCH: usize = {};\n",
        m.slab_release_batch
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_CROSS_CPU_STEAL: bool = {};\n",
        m.slab_cross_cpu_steal
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_RECLAIM_PROFILE: &str = \"{}\";\n",
        m.slab_reclaim_profile
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_PRESSURE_SCAN_BUDGET: usize = {};\n",
        m.slab_pressure_scan_budget.max(1)
    ));
    c.push_str(&format!(
        "pub const MEM_SLAB_MAX_TRACKED_SEGMENTS: usize = {};\n",
        m.slab_max_tracked_segments.max(64)
    ));
    c.push_str(&format!(
        "pub const MEM_COMPACTION_BUDGET_PAGES: usize = {};\n",
        m.compaction_budget_pages
    ));
    c.push_str(&format!(
        "pub const MEM_OOM_KILL_THRESHOLD: u64 = {};\n",
        m.oom_kill_threshold
    ));
    c.push_str(&format!(
        "pub const MEM_PREFER_LOCAL_NUMA: bool = {};\n",
        m.prefer_local_numa
    ));
    c.push_str(&format!(
        "pub const MEM_POOL_BLOCK_SIZE: usize = {};\n",
        m.pool_block_size
    ));
}

fn emit_scheduler(c: &mut String, config: &Config) {
    let s = &config.scheduler;
    c.push_str(&format!(
        "pub const SCHED_PRIORITY_LEVELS: usize = {};\n",
        s.priority_levels
    ));

    if let Some(rr) = &s.round_robin {
        c.push_str(&format!(
            "pub const SCHED_RR_MAX_TASKS: usize = {};\n",
            rr.max_tasks
        ));
        c.push_str(&format!(
            "pub const SCHED_RR_DEFAULT_SLICE_NS: u64 = {};\n",
            rr.default_slice_ns
        ));
    }

    if let Some(cfs) = &s.cfs {
        c.push_str(&format!(
            "pub const SCHED_CFS_MIN_GRANULARITY_NS: u64 = {};\n",
            cfs.min_granularity_ns
        ));
        c.push_str(&format!(
            "pub const SCHED_CFS_LATENCY_TARGET_NS: u64 = {};\n",
            cfs.latency_target_ns
        ));
    }

    if let Some(edf) = &s.edf {
        c.push_str(&format!(
            "pub const SCHED_EDF_MAX_DEADLINES: usize = {};\n",
            edf.max_deadlines
        ));
        c.push_str(&format!(
            "pub const SCHED_EDF_ENFORCE_DEADLINE: bool = {};\n",
            edf.enforce_deadline
        ));
        c.push_str(&format!(
            "pub const SCHED_EDF_DEFAULT_RELATIVE_DEADLINE_NS: u64 = {};\n",
            edf.default_relative_deadline_ns
        ));
    } else {
        c.push_str("pub const SCHED_EDF_MAX_DEADLINES: usize = 128;\n");
        c.push_str("pub const SCHED_EDF_ENFORCE_DEADLINE: bool = true;\n");
        c.push_str("pub const SCHED_EDF_DEFAULT_RELATIVE_DEADLINE_NS: u64 = 8000000;\n");
    }

    if let Some(mlfq) = &s.mlfq {
        c.push_str(&format!(
            "pub const SCHED_MLFQ_NUM_QUEUES: usize = {};\n",
            mlfq.num_queues
        ));
        c.push_str(&format!(
            "pub const SCHED_MLFQ_BASE_SLICE_NS: u64 = {};\n",
            mlfq.base_slice_ns
        ));
        c.push_str(&format!(
            "pub const SCHED_MLFQ_BOOST_INTERVAL_TICKS: u64 = {};\n",
            mlfq.boost_interval_ticks
        ));
        c.push_str(&format!(
            "pub const SCHED_MLFQ_DEMOTE_ON_SLICE_EXHAUSTION: bool = {};\n",
            mlfq.demote_on_slice_exhaustion
        ));
    } else {
        c.push_str("pub const SCHED_MLFQ_NUM_QUEUES: usize = 4;\n");
        c.push_str("pub const SCHED_MLFQ_BASE_SLICE_NS: u64 = 1000000;\n");
        c.push_str("pub const SCHED_MLFQ_BOOST_INTERVAL_TICKS: u64 = 250;\n");
        c.push_str("pub const SCHED_MLFQ_DEMOTE_ON_SLICE_EXHAUSTION: bool = true;\n");
    }

    if let Some(rt) = &s.rt {
        c.push_str(&format!(
            "pub const SCHED_RT_ENABLE_GROUP_RESERVATION: bool = {};\n",
            rt.enable_group_reservation
        ));
        c.push_str(&format!(
            "pub const SCHED_RT_PERIOD_NS: u64 = {};\n",
            rt.period_ns
        ));
        c.push_str(&format!(
            "pub const SCHED_RT_TOTAL_UTILIZATION_CAP_PERCENT: u8 = {};\n",
            rt.total_utilization_cap_percent
        ));
        c.push_str(&format!(
            "pub const SCHED_RT_MAX_GROUPS: usize = {};\n",
            rt.max_groups
        ));
    } else {
        c.push_str("pub const SCHED_RT_ENABLE_GROUP_RESERVATION: bool = false;\n");
        c.push_str("pub const SCHED_RT_PERIOD_NS: u64 = 100000000;\n");
        c.push_str("pub const SCHED_RT_TOTAL_UTILIZATION_CAP_PERCENT: u8 = 80;\n");
        c.push_str("pub const SCHED_RT_MAX_GROUPS: usize = 8;\n");
    }

    // Additional constants needed by source
    c.push_str("pub const WRR_MAX_WEIGHT: usize = 2000;\n");
    c.push_str("pub const FIFO_ALLOW_PREEMPTION: bool = false;\n");
    c.push_str(&format!(
        "pub const RR_MAX_TASKS: usize = {};\n",
        s.round_robin
            .as_ref()
            .map(|rr| rr.max_tasks)
            .unwrap_or(1024)
    ));
}

fn emit_ipc(c: &mut String, config: &Config) {
    let i = &config.ipc;
    c.push_str(&format!(
        "pub const IPC_MAX_CHANNELS: usize = {};\n",
        i.max_channels
    ));
    c.push_str(&format!(
        "pub const IPC_MSG_SIZE_LIMIT: usize = {};\n",
        i.msg_size_limit
    ));
    c.push_str(&format!(
        "pub const IPC_RING_BUFFER_SIZE_BYTES: usize = {};\n",
        i.ring_buffer_size_kb * 1024
    ));
    c.push_str(&format!(
        "pub const IPC_UNIX_SOCKET_QUEUE_LIMIT: usize = {};\n",
        i.unix_socket_queue_limit
    ));
    c.push_str(&format!(
        "pub const IPC_BINDER_MAX_OBJECTS: usize = {};\n",
        i.binder_max_objects
    ));
    c.push_str(&format!(
        "pub const IPC_FUTEX_WAKE_EVENT_LIMIT: usize = {};\n",
        i.futex_wake_event_limit
    ));
}

fn emit_security(c: &mut String, config: &Config) {
    let s = &config.security;
    c.push_str(&format!(
        "pub const SECURITY_NX_BIT: bool = {};\n",
        s.nx_bit
    ));
    c.push_str(&format!(
        "pub const SECURITY_SMAP_SMEP: bool = {};\n",
        s.smap_smep
    ));
    c.push_str(&format!(
        "pub const SECURITY_ZERO_TRUST: bool = {};\n",
        s.zero_trust_mode
    ));
    c.push_str(&format!(
        "pub const SECURITY_ENABLE_MAC: bool = {};\n",
        s.enable_mac
    ));
    c.push_str(&format!(
        "pub const SECURITY_ENABLE_AUDIT: bool = {};\n",
        s.enable_audit
    ));
    c.push_str(&format!(
        "pub const SECURITY_MAX_LABELS: usize = {};\n",
        s.max_security_labels
    ));
    c.push_str(&format!(
        "pub const SECURITY_MAX_CAP_TOKENS: usize = {};\n",
        s.max_capability_tokens
    ));
    c.push_str(&format!(
        "pub const SECURITY_DEFAULT_USER_CAPS: u64 = {};\n",
        s.default_user_capabilities
    ));
}

fn emit_telemetry(c: &mut String, config: &Config) {
    let t = &config.telemetry;
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLED: bool = {};\n",
        t.enabled
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_HISTORY_LEN: usize = {};\n",
        t.history_len
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_RUNTIME_SUMMARY: bool = {};\n",
        t.runtime_summary
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_VFS: bool = {};\n",
        t.vfs
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_NETWORK: bool = {};\n",
        t.network
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_IPC: bool = {};\n",
        t.ipc
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_SCHEDULER: bool = {};\n",
        t.scheduler
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_SECURITY: bool = {};\n",
        t.security
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_POWER: bool = {};\n",
        t.power
    ));
    c.push_str(&format!(
        "pub const TELEMETRY_ENABLE_DRIVERS: bool = {};\n",
        t.drivers
    ));
    c.push_str(&format!(
        "pub const LOG_LEVEL: &str = \"{}\";\n",
        t.log_level
    ));
}

fn emit_linux_compat(c: &mut String, config: &Config) {
    let l = &config.linux_compat;
    c.push_str(&format!(
        "pub const LINUX_MAX_PATH_LEN: usize = {};\n",
        l.max_path_len
    ));
    c.push_str(&format!(
        "pub const LINUX_MAX_IOV_COUNT: usize = {};\n",
        l.max_iov_count
    ));
    c.push_str(&format!(
        "pub const LINUX_MAX_SOCKADDR_LEN: usize = {};\n",
        l.max_sockaddr_len
    ));
    c.push_str(&format!(
        "pub const LINUX_MAX_XATTR_NAME_LEN: usize = {};\n",
        l.max_xattr_name_len
    ));
    c.push_str(&format!(
        "pub const LINUX_MAX_XATTR_VALUE_SIZE: usize = {};\n",
        l.max_xattr_value_size
    ));
    c.push_str(&format!(
        "pub const LINUX_DEFAULT_PIPE_SIZE: usize = {};\n",
        l.default_pipe_size
    ));
    c.push_str(&format!(
        "pub const LINUX_MAX_MOUNT_PATH: usize = {};\n",
        l.max_mount_path
    ));
    c.push_str(&format!(
        "pub const LINUX_STAT_BLOCK_SIZE: u64 = {};\n",
        l.stat_block_size
    ));
    c.push_str(&format!(
        "pub const LINUX_STAT_BLKSIZE: u32 = {};\n",
        l.stat_blksize
    ));
    c.push_str(&format!(
        "pub const LINUX_MOUNT_CTX_FD_BASE: i32 = {};\n",
        l.mount_ctx_fd_base
    ));
    c.push_str(&format!(
        "pub const LINUX_MOUNT_FD_BASE: i32 = {};\n",
        l.mount_fd_base
    ));
    c.push_str(&format!(
        "pub const LINUX_LEGACY_SUPPORT: bool = {};\n",
        l.legacy_support
    ));
    c.push_str(&format!(
        "pub const LINUX_FUTEX_WAITV_MAX: usize = {};\n",
        l.futex_waitv_max
    ));
    c.push_str(&format!(
        "pub const LINUX_ROBUST_LIST_HEAD_SIZE: usize = {};\n",
        l.robust_list_head_size
    ));
    c.push_str(&format!(
        "pub const LINUX_ENABLE_STANDARD_ERROR_MAPPING: bool = {};\n",
        l.enable_standard_error_mapping
    ));
    c.push_str(&format!(
        "pub const LINUX_VERBOSE_SYSCALL_LOGS: bool = {};\n",
        l.verbose_syscall_logs
    ));
}

fn emit_vfs(c: &mut String, config: &Config) {
    let v = &config.vfs;
    c.push_str(&format!(
        "pub const VFS_MAX_MOUNTS: usize = {};\n",
        v.max_mounts
    ));
    c.push_str(&format!(
        "pub const VFS_MAX_MOUNT_PATH: usize = {};\n",
        v.max_mount_path
    ));
    c.push_str(&format!(
        "pub const VFS_ENABLE_BUFFERED_IO_STUB: bool = {};\n",
        v.enable_buffered_io
    ));
    c.push_str(&format!(
        "pub const VFS_HEALTH_SLO_MS: u64 = {};\n",
        v.health_slo_ms
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_DEFAULT_MODE: u32 = {};\n",
        v.devfs_default_mode
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_DEFAULT_UID: u32 = {};\n",
        v.devfs_default_uid
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_DEFAULT_GID: u32 = {};\n",
        v.devfs_default_gid
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_POLICY_PROFILE: &str = \"{}\";\n",
        v.devfs_policy_profile
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_NET_MODE: u32 = {};\n",
        v.devfs_net_mode
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_NET_GID: u32 = {};\n",
        v.devfs_net_gid
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_STORAGE_MODE: u32 = {};\n",
        v.devfs_storage_mode
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_STORAGE_GID: u32 = {};\n",
        v.devfs_storage_gid
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_ENABLE_HOTPLUG_NET_NODES: bool = {};\n",
        v.devfs_enable_hotplug_net_nodes
    ));
    c.push_str(&format!(
        "pub const VFS_DEVFS_ENABLE_HOTPLUG_STORAGE_NODES: bool = {};\n",
        v.devfs_enable_hotplug_storage_nodes
    ));
}

fn emit_network(c: &mut String, config: &Config) {
    let n = &config.network;
    c.push_str(&format!(
        "pub const NETWORK_LOOPBACK_QUEUE_LIMIT: usize = {};\n",
        n.loopback_queue_limit
    ));
    c.push_str(&format!(
        "pub const NETWORK_UDP_QUEUE_LIMIT: usize = {};\n",
        n.udp_queue_limit
    ));
    c.push_str(&format!(
        "pub const NETWORK_TCP_QUEUE_LIMIT: usize = {};\n",
        n.tcp_queue_limit
    ));
    c.push_str(&format!(
        "pub const NETWORK_FILTER_RULE_LIMIT: usize = {};\n",
        n.filter_rule_limit
    ));
    c.push_str(&format!(
        "pub const NETWORK_WIREGUARD_MAX_PEERS: usize = {};\n",
        n.wireguard_max_peers
    ));
    c.push_str(&format!(
        "pub const NETWORK_HTTP_ASSET_LIMIT: usize = {};\n",
        n.http_asset_limit
    ));
    c.push_str(&format!(
        "pub const NETWORK_TLS_POLICY_PROFILE: &str = \"{}\";\n",
        n.tls_policy_profile
    ));
    c.push_str(&format!(
        "pub const NETWORK_POSIX_FD_START: u32 = {};\n",
        n.posix_fd_start
    ));
    c.push_str(&format!(
        "pub const NETWORK_POSIX_EPHEMERAL_START: u16 = {};\n",
        n.posix_ephemeral_start
    ));
    c.push_str(&format!(
        "pub const NETWORK_BLOCKING_RECV_RETRIES: usize = {};\n",
        n.blocking_recv_retries
    ));
    c.push_str(&format!(
        "pub const NETWORK_SLO_SAMPLE_INTERVAL: u64 = {};\n",
        n.slo_sample_interval
    ));
    c.push_str(&format!(
        "pub const NETWORK_SLO_LOG_INTERVAL_MULTIPLIER: u64 = {};\n",
        n.slo_log_interval_multiplier
    ));
}

fn emit_drivers(c: &mut String, config: &Config) {
    let d = &config.drivers;
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_IRQ_SERVICE_BUDGET: usize = {};\n",
        d.network_irq_service_budget
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_LOOP_SERVICE_BUDGET: usize = {};\n",
        d.network_loop_service_budget
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_RING_LIMIT: usize = {};\n",
        d.network_ring_limit
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_QUARANTINE_REBIND_FAILURES: u64 = {};\n",
        d.network_quarantine_rebind_failures
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_QUARANTINE_COOLDOWN_SAMPLES: u64 = {};\n",
        d.network_quarantine_cooldown_samples
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_SLO_MAX_DROP_RATE_PER_MILLE: u64 = {};\n",
        d.network_slo_max_drop_rate_per_mille
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_SLO_MAX_TX_RING_UTILIZATION_PERCENT: u64 = {};\n",
        d.network_slo_max_tx_ring_utilization_percent
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_SLO_MAX_RX_RING_UTILIZATION_PERCENT: u64 = {};\n",
        d.network_slo_max_rx_ring_utilization_percent
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_SLO_MAX_IO_ERRORS: u64 = {};\n",
        d.network_slo_max_io_errors
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_LOW_LATENCY_IRQ_BUDGET_DIVISOR: usize = {};\n",
        d.network_low_latency_irq_budget_divisor
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_LOW_LATENCY_LOOP_BUDGET_DIVISOR: usize = {};\n",
        d.network_low_latency_loop_budget_divisor
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_LOW_LATENCY_RING_LIMIT_DIVISOR: usize = {};\n",
        d.network_low_latency_ring_limit_divisor
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_THROUGHPUT_IRQ_BUDGET_MULTIPLIER: usize = {};\n",
        d.network_throughput_irq_budget_multiplier
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_THROUGHPUT_LOOP_BUDGET_MULTIPLIER: usize = {};\n",
        d.network_throughput_loop_budget_multiplier
    ));
    c.push_str(&format!(
        "pub const DRIVER_NETWORK_THROUGHPUT_RING_LIMIT_MULTIPLIER: usize = {};\n",
        d.network_throughput_ring_limit_multiplier
    ));
    c.push_str(&format!(
        "pub const DRIVER_AHCI_IO_TIMEOUT_SPINS: usize = {};\n",
        d.ahci_io_timeout_spins
    ));
    c.push_str(&format!(
        "pub const DRIVER_NVME_DISABLE_READY_TIMEOUT_SPINS: usize = {};\n",
        d.nvme_disable_ready_timeout_spins
    ));
    c.push_str(&format!(
        "pub const DRIVER_NVME_POLL_TIMEOUT_SPINS: usize = {};\n",
        d.nvme_poll_timeout_spins
    ));
    c.push_str(&format!(
        "pub const DRIVER_NVME_IO_TIMEOUT_SPINS: usize = {};\n",
        d.nvme_io_timeout_spins
    ));
    c.push_str(&format!(
        "pub const DRIVER_E1000_RESET_TIMEOUT_SPINS: usize = {};\n",
        d.e1000_reset_timeout_spins
    ));
    c.push_str(&format!(
        "pub const DRIVER_E1000_BUFFER_SIZE_BYTES: usize = {};\n",
        d.e1000_buffer_size_bytes
    ));
    c.push_str(&format!(
        "pub const DRIVER_E1000_RX_DESC_COUNT: usize = {};\n",
        d.e1000_rx_desc_count
    ));
    c.push_str(&format!(
        "pub const DRIVER_E1000_TX_DESC_COUNT: usize = {};\n",
        d.e1000_tx_desc_count
    ));
}

fn emit_governor(c: &mut String, config: &Config) {
    let g = &config.governor;
    c.push_str(&format!(
        "pub const GOVERNOR_WATCHDOG_HARD_STALL_NS: u64 = {};\n",
        g.watchdog_hard_stall_ns
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_RT_FORCE_MIN_TICKS: usize = {};\n",
        g.rt_force_min_ticks
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_RT_DEADLINE_BURST_THRESHOLD: usize = {};\n",
        g.rt_deadline_burst_threshold
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_IRQSAFE_MUTEX_DEADLOCK_SPIN_LIMIT: usize = {};\n",
        g.irqsafe_mutex_deadlock_spin_limit
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_POWER_RUNQUEUE_SATURATION_LIMIT: usize = {};\n",
        g.power_runqueue_saturation_limit
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_LOAD_BALANCE_PERCENTILE_WINDOW: usize = {};\n",
        g.load_balance_percentile_window.max(1)
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_RUNTIME_POLICY_DRIFT_SAMPLE_INTERVAL_TICKS: u64 = {};\n",
        g.runtime_policy_drift_sample_interval_ticks.max(1)
    ));
    c.push_str(&format!(
        "pub const GOVERNOR_RUNTIME_POLICY_DRIFT_REAPPLY_COOLDOWN_TICKS: u64 = {};\n",
        g.runtime_policy_drift_reapply_cooldown_ticks.max(1)
    ));
}

fn emit_aarch64(c: &mut String, config: &Config) {
    let a = &config.aarch64;
    let ecam_bases = if a.pci_ecam_bases.is_empty() {
        vec![0x1000_0000u64, 0x3F00_0000u64]
    } else {
        a.pci_ecam_bases.clone()
    };
    let ecam_list = ecam_bases
        .iter()
        .map(|v| format!("0x{:x}u64", v))
        .collect::<Vec<_>>()
        .join(", ");
    c.push_str(&format!(
        "pub const AARCH64_PCI_ECAM_BASES: [u64; {}] = [{}];\n",
        ecam_bases.len(),
        ecam_list
    ));
    c.push_str(&format!(
        "pub const AARCH64_PCI_SCAN_STOP_ON_FIRST_HIT: bool = {};\n",
        a.pci_scan_stop_on_first_hit
    ));
    c.push_str(&format!(
        "pub const AARCH64_PCI_MAX_BUS: u16 = {};\n",
        a.pci_max_bus
    ));
    c.push_str(&format!(
        "pub const AARCH64_PCI_MAX_DEVICE: u8 = {};\n",
        a.pci_max_device
    ));
    c.push_str(&format!(
        "pub const AARCH64_PCI_MAX_FUNCTION: u8 = {};\n",
        a.pci_max_function
    ));
    c.push_str(&format!(
        "pub const AARCH64_SMP_BOOT_TIMEOUT_SPINS: u64 = {};\n",
        a.smp_boot_timeout_spins
    ));
    c.push_str(&format!(
        "pub const AARCH64_EXCEPTION_KILL_USER_SYNC: bool = {};\n",
        a.exception_kill_user_sync
    ));
    c.push_str(&format!(
        "pub const AARCH64_EXCEPTION_KILL_USER_ASYNC: bool = {};\n",
        a.exception_kill_user_async
    ));
    c.push_str(&format!(
        "pub const AARCH64_EXCEPTION_PANIC_ON_KERNEL_SYNC: bool = {};\n",
        a.exception_panic_on_kernel_sync
    ));
    c.push_str(&format!(
        "pub const AARCH64_EXCEPTION_PANIC_ON_KERNEL_ASYNC: bool = {};\n",
        a.exception_panic_on_kernel_async
    ));
    c.push_str(&format!(
        "pub const AARCH64_IRQ_STORM_WINDOW_TICKS: u64 = {};\n",
        a.irq_storm_window_ticks
    ));
    c.push_str(&format!(
        "pub const AARCH64_IRQ_STORM_THRESHOLD: u64 = {};\n",
        a.irq_storm_threshold
    ));
    c.push_str(&format!(
        "pub const AARCH64_IRQ_STORM_LOG_EVERY: u64 = {};\n",
        a.irq_storm_log_every
    ));
    c.push_str(&format!(
        "pub const AARCH64_TIMER_REARM_MIN_TICKS: u64 = {};\n",
        a.timer_rearm_min_ticks
    ));
    c.push_str(&format!(
        "pub const AARCH64_TIMER_REARM_MAX_TICKS: u64 = {};\n",
        a.timer_rearm_max_ticks
    ));
    c.push_str(&format!(
        "pub const AARCH64_TIMER_JITTER_TOLERANCE_TICKS: u64 = {};\n",
        a.timer_jitter_tolerance_ticks
    ));
    c.push_str(&format!(
        "pub const AARCH64_GIC_CPU_PRIORITY_MASK: u32 = {};\n",
        a.gic_cpu_priority_mask
    ));
    c.push_str(&format!(
        "pub const AARCH64_IRQ_RATE_TRACK_LIMIT: usize = {};\n",
        a.irq_rate_track_limit
    ));
    c.push_str(&format!(
        "pub const AARCH64_IRQ_PER_LINE_STORM_THRESHOLD: u64 = {};\n",
        a.irq_per_line_storm_threshold
    ));
    c.push_str(&format!(
        "pub const AARCH64_IRQ_PER_LINE_LOG_EVERY: u64 = {};\n",
        a.irq_per_line_log_every
    ));
    c.push_str(&format!(
        "pub const AARCH64_TLB_SHOOTDOWN_TIMEOUT_SPINS: usize = {};\n",
        a.tlb_shootdown_timeout_spins.max(1)
    ));

    let smp_known_mpidrs = if a.smp_known_mpidrs.is_empty() {
        vec![0x0000_0001u64, 0x0000_0002u64, 0x0000_0003u64]
    } else {
        a.smp_known_mpidrs.clone()
    };
    let smp_list = smp_known_mpidrs
        .iter()
        .map(|v| format!("0x{:x}u64", v))
        .collect::<Vec<_>>()
        .join(", ");
    c.push_str(&format!(
        "pub const AARCH64_SMP_KNOWN_MPIDRS: [u64; {}] = [{}];\n",
        smp_known_mpidrs.len(),
        smp_list
    ));
}

fn emit_lottery(c: &mut String, config: &Config) {
    let l = &config.lottery;
    c.push_str(&format!(
        "pub const SCHED_LOTTERY_INITIAL_SEED: u64 = {};\n",
        l.initial_seed
    ));
    c.push_str(&format!(
        "pub const SCHED_LOTTERY_TICKETS_PER_PRIORITY: u64 = {};\n",
        l.tickets_per_priority_level
    ));
    c.push_str(&format!(
        "pub const SCHED_LOTTERY_MIN_TICKETS: u64 = {};\n",
        l.min_tickets_per_task
    ));
    c.push_str(&format!(
        "pub const SCHED_LOTTERY_REPLAY_TRACE_CAPACITY: usize = {};\n",
        l.replay_trace_capacity.max(1)
    ));
    c.push_str(&format!(
        "pub const SCHED_LOTTERY_LCG_MULTIPLIER: u64 = {};\n",
        l.lcg_multiplier.max(1)
    ));
    c.push_str(&format!(
        "pub const SCHED_LOTTERY_LCG_INCREMENT: u64 = {};\n",
        l.lcg_increment.max(1)
    ));
}

fn emit_feature_catalog(c: &mut String) {
    let feature_graph = load_feature_graph_from_manifest();
    let feature_names: Vec<String> = feature_graph.keys().cloned().collect();
    let count = feature_names.len();

    let names_joined = feature_names
        .iter()
        .map(|n| format!("\"{}\"", n))
        .collect::<Vec<_>>()
        .join(", ");
    let enabled_joined = feature_names
        .iter()
        .map(|n| if feature_enabled(n) { "true" } else { "false" }.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let primary_group_joined = feature_names
        .iter()
        .map(|n| format!("\"{}\"", feature_primary_group(n, &feature_graph)))
        .collect::<Vec<_>>()
        .join(", ");

    c.push_str(&format!(
        "pub const CARGO_FEATURE_COUNT: usize = {};\n",
        count
    ));
    c.push_str(&format!(
        "pub const CARGO_FEATURE_NAMES: [&str; {}] = [{}];\n",
        count, names_joined
    ));
    c.push_str(&format!(
        "pub const CARGO_FEATURE_ENABLED: [bool; {}] = [{}];\n",
        count, enabled_joined
    ));
    c.push_str(&format!(
        "pub const CARGO_FEATURE_PRIMARY_GROUP: [&str; {}] = [{}];\n",
        count, primary_group_joined
    ));
}
